/* tslint:disable */
/* eslint-disable */
/**
 * zzirit API
 * 찌릿 API 명세서
 *
 * The version of the OpenAPI document: v0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AddressUpdateRequest
 */
export interface AddressUpdateRequest {
    /**
     * 
     * @type {string}
     * @memberof AddressUpdateRequest
     */
    memberAddress: string;
    /**
     * 
     * @type {string}
     * @memberof AddressUpdateRequest
     */
    memberAddressDetail?: string;
}

/**
 * Check if a given object implements the AddressUpdateRequest interface.
 */
export function instanceOfAddressUpdateRequest(value: object): value is AddressUpdateRequest {
    if (!('memberAddress' in value) || value['memberAddress'] === undefined) return false;
    return true;
}

export function AddressUpdateRequestFromJSON(json: any): AddressUpdateRequest {
    return AddressUpdateRequestFromJSONTyped(json, false);
}

export function AddressUpdateRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): AddressUpdateRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'memberAddress': json['memberAddress'],
        'memberAddressDetail': json['memberAddressDetail'] == null ? undefined : json['memberAddressDetail'],
    };
}

export function AddressUpdateRequestToJSON(json: any): AddressUpdateRequest {
    return AddressUpdateRequestToJSONTyped(json, false);
}

export function AddressUpdateRequestToJSONTyped(value?: AddressUpdateRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'memberAddress': value['memberAddress'],
        'memberAddressDetail': value['memberAddressDetail'],
    };
}

