/* tslint:disable */
/* eslint-disable */
/**
 * zzirit API
 * 찌릿 API 명세서
 *
 * The version of the OpenAPI document: v0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { OrderFetchResponse } from './OrderFetchResponse';
import {
    OrderFetchResponseFromJSON,
    OrderFetchResponseFromJSONTyped,
    OrderFetchResponseToJSON,
    OrderFetchResponseToJSONTyped,
} from './OrderFetchResponse';

/**
 * 
 * @export
 * @interface BaseResponseListOrderFetchResponse
 */
export interface BaseResponseListOrderFetchResponse {
    /**
     * 
     * @type {boolean}
     * @memberof BaseResponseListOrderFetchResponse
     */
    success?: boolean;
    /**
     * 
     * @type {number}
     * @memberof BaseResponseListOrderFetchResponse
     */
    code?: number;
    /**
     * 
     * @type {number}
     * @memberof BaseResponseListOrderFetchResponse
     */
    httpStatus?: number;
    /**
     * 
     * @type {string}
     * @memberof BaseResponseListOrderFetchResponse
     */
    message?: string;
    /**
     * 
     * @type {Array<OrderFetchResponse>}
     * @memberof BaseResponseListOrderFetchResponse
     */
    result?: Array<OrderFetchResponse>;
}

/**
 * Check if a given object implements the BaseResponseListOrderFetchResponse interface.
 */
export function instanceOfBaseResponseListOrderFetchResponse(value: object): value is BaseResponseListOrderFetchResponse {
    return true;
}

export function BaseResponseListOrderFetchResponseFromJSON(json: any): BaseResponseListOrderFetchResponse {
    return BaseResponseListOrderFetchResponseFromJSONTyped(json, false);
}

export function BaseResponseListOrderFetchResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): BaseResponseListOrderFetchResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'success': json['success'] == null ? undefined : json['success'],
        'code': json['code'] == null ? undefined : json['code'],
        'httpStatus': json['httpStatus'] == null ? undefined : json['httpStatus'],
        'message': json['message'] == null ? undefined : json['message'],
        'result': json['result'] == null ? undefined : ((json['result'] as Array<any>).map(OrderFetchResponseFromJSON)),
    };
}

export function BaseResponseListOrderFetchResponseToJSON(json: any): BaseResponseListOrderFetchResponse {
    return BaseResponseListOrderFetchResponseToJSONTyped(json, false);
}

export function BaseResponseListOrderFetchResponseToJSONTyped(value?: BaseResponseListOrderFetchResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'success': value['success'],
        'code': value['code'],
        'httpStatus': value['httpStatus'],
        'message': value['message'],
        'result': value['result'] == null ? undefined : ((value['result'] as Array<any>).map(OrderFetchResponseToJSON)),
    };
}

