/* tslint:disable */
/* eslint-disable */
/**
 * zzirit API
 * 찌릿 API 명세서
 *
 * The version of the OpenAPI document: v0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface BaseResponseObject
 */
export interface BaseResponseObject {
    /**
     * 
     * @type {boolean}
     * @memberof BaseResponseObject
     */
    success?: boolean;
    /**
     * 
     * @type {number}
     * @memberof BaseResponseObject
     */
    code?: number;
    /**
     * 
     * @type {number}
     * @memberof BaseResponseObject
     */
    httpStatus?: number;
    /**
     * 
     * @type {string}
     * @memberof BaseResponseObject
     */
    message?: string;
    /**
     * 
     * @type {object}
     * @memberof BaseResponseObject
     */
    result?: object;
}

/**
 * Check if a given object implements the BaseResponseObject interface.
 */
export function instanceOfBaseResponseObject(value: object): value is BaseResponseObject {
    return true;
}

export function BaseResponseObjectFromJSON(json: any): BaseResponseObject {
    return BaseResponseObjectFromJSONTyped(json, false);
}

export function BaseResponseObjectFromJSONTyped(json: any, ignoreDiscriminator: boolean): BaseResponseObject {
    if (json == null) {
        return json;
    }
    return {
        
        'success': json['success'] == null ? undefined : json['success'],
        'code': json['code'] == null ? undefined : json['code'],
        'httpStatus': json['httpStatus'] == null ? undefined : json['httpStatus'],
        'message': json['message'] == null ? undefined : json['message'],
        'result': json['result'] == null ? undefined : json['result'],
    };
}

export function BaseResponseObjectToJSON(json: any): BaseResponseObject {
    return BaseResponseObjectToJSONTyped(json, false);
}

export function BaseResponseObjectToJSONTyped(value?: BaseResponseObject | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'success': value['success'],
        'code': value['code'],
        'httpStatus': value['httpStatus'],
        'message': value['message'],
        'result': value['result'],
    };
}

