/* tslint:disable */
/* eslint-disable */
/**
 * zzirit API
 * 찌릿 API 명세서
 *
 * The version of the OpenAPI document: v0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Member } from './Member';
import {
    MemberFromJSON,
    MemberFromJSONTyped,
    MemberToJSON,
    MemberToJSONTyped,
} from './Member';

/**
 * 
 * @export
 * @interface BaseResponseMember
 */
export interface BaseResponseMember {
    /**
     * 
     * @type {boolean}
     * @memberof BaseResponseMember
     */
    success?: boolean;
    /**
     * 
     * @type {number}
     * @memberof BaseResponseMember
     */
    code?: number;
    /**
     * 
     * @type {number}
     * @memberof BaseResponseMember
     */
    httpStatus?: number;
    /**
     * 
     * @type {string}
     * @memberof BaseResponseMember
     */
    message?: string;
    /**
     * 
     * @type {Member}
     * @memberof BaseResponseMember
     */
    result?: Member;
}

/**
 * Check if a given object implements the BaseResponseMember interface.
 */
export function instanceOfBaseResponseMember(value: object): value is BaseResponseMember {
    return true;
}

export function BaseResponseMemberFromJSON(json: any): BaseResponseMember {
    return BaseResponseMemberFromJSONTyped(json, false);
}

export function BaseResponseMemberFromJSONTyped(json: any, ignoreDiscriminator: boolean): BaseResponseMember {
    if (json == null) {
        return json;
    }
    return {
        
        'success': json['success'] == null ? undefined : json['success'],
        'code': json['code'] == null ? undefined : json['code'],
        'httpStatus': json['httpStatus'] == null ? undefined : json['httpStatus'],
        'message': json['message'] == null ? undefined : json['message'],
        'result': json['result'] == null ? undefined : MemberFromJSON(json['result']),
    };
}

export function BaseResponseMemberToJSON(json: any): BaseResponseMember {
    return BaseResponseMemberToJSONTyped(json, false);
}

export function BaseResponseMemberToJSONTyped(value?: BaseResponseMember | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'success': value['success'],
        'code': value['code'],
        'httpStatus': value['httpStatus'],
        'message': value['message'],
        'result': MemberToJSON(value['result']),
    };
}

