/* tslint:disable */
/* eslint-disable */
/**
 * zzirit API
 * 찌릿 API 명세서
 *
 * The version of the OpenAPI document: v0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { CartFetchResponse } from './CartFetchResponse';
import {
    CartFetchResponseFromJSON,
    CartFetchResponseFromJSONTyped,
    CartFetchResponseToJSON,
    CartFetchResponseToJSONTyped,
} from './CartFetchResponse';

/**
 * 
 * @export
 * @interface BaseResponseCartFetchResponse
 */
export interface BaseResponseCartFetchResponse {
    /**
     * 
     * @type {boolean}
     * @memberof BaseResponseCartFetchResponse
     */
    success?: boolean;
    /**
     * 
     * @type {number}
     * @memberof BaseResponseCartFetchResponse
     */
    code?: number;
    /**
     * 
     * @type {number}
     * @memberof BaseResponseCartFetchResponse
     */
    httpStatus?: number;
    /**
     * 
     * @type {string}
     * @memberof BaseResponseCartFetchResponse
     */
    message?: string;
    /**
     * 
     * @type {CartFetchResponse}
     * @memberof BaseResponseCartFetchResponse
     */
    result?: CartFetchResponse;
}

/**
 * Check if a given object implements the BaseResponseCartFetchResponse interface.
 */
export function instanceOfBaseResponseCartFetchResponse(value: object): value is BaseResponseCartFetchResponse {
    return true;
}

export function BaseResponseCartFetchResponseFromJSON(json: any): BaseResponseCartFetchResponse {
    return BaseResponseCartFetchResponseFromJSONTyped(json, false);
}

export function BaseResponseCartFetchResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): BaseResponseCartFetchResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'success': json['success'] == null ? undefined : json['success'],
        'code': json['code'] == null ? undefined : json['code'],
        'httpStatus': json['httpStatus'] == null ? undefined : json['httpStatus'],
        'message': json['message'] == null ? undefined : json['message'],
        'result': json['result'] == null ? undefined : CartFetchResponseFromJSON(json['result']),
    };
}

export function BaseResponseCartFetchResponseToJSON(json: any): BaseResponseCartFetchResponse {
    return BaseResponseCartFetchResponseToJSONTyped(json, false);
}

export function BaseResponseCartFetchResponseToJSONTyped(value?: BaseResponseCartFetchResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'success': value['success'],
        'code': value['code'],
        'httpStatus': value['httpStatus'],
        'message': value['message'],
        'result': CartFetchResponseToJSON(value['result']),
    };
}

