/* tslint:disable */
/* eslint-disable */
/**
 * zzirit API
 * 찌릿 API 명세서
 *
 * The version of the OpenAPI document: v0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PageResponseTimeDealFetchResponse } from './PageResponseTimeDealFetchResponse';
import {
    PageResponseTimeDealFetchResponseFromJSON,
    PageResponseTimeDealFetchResponseFromJSONTyped,
    PageResponseTimeDealFetchResponseToJSON,
    PageResponseTimeDealFetchResponseToJSONTyped,
} from './PageResponseTimeDealFetchResponse';

/**
 * 
 * @export
 * @interface BaseResponsePageResponseTimeDealFetchResponse
 */
export interface BaseResponsePageResponseTimeDealFetchResponse {
    /**
     * 
     * @type {boolean}
     * @memberof BaseResponsePageResponseTimeDealFetchResponse
     */
    success?: boolean;
    /**
     * 
     * @type {number}
     * @memberof BaseResponsePageResponseTimeDealFetchResponse
     */
    code?: number;
    /**
     * 
     * @type {number}
     * @memberof BaseResponsePageResponseTimeDealFetchResponse
     */
    httpStatus?: number;
    /**
     * 
     * @type {string}
     * @memberof BaseResponsePageResponseTimeDealFetchResponse
     */
    message?: string;
    /**
     * 
     * @type {PageResponseTimeDealFetchResponse}
     * @memberof BaseResponsePageResponseTimeDealFetchResponse
     */
    result?: PageResponseTimeDealFetchResponse;
}

/**
 * Check if a given object implements the BaseResponsePageResponseTimeDealFetchResponse interface.
 */
export function instanceOfBaseResponsePageResponseTimeDealFetchResponse(value: object): value is BaseResponsePageResponseTimeDealFetchResponse {
    return true;
}

export function BaseResponsePageResponseTimeDealFetchResponseFromJSON(json: any): BaseResponsePageResponseTimeDealFetchResponse {
    return BaseResponsePageResponseTimeDealFetchResponseFromJSONTyped(json, false);
}

export function BaseResponsePageResponseTimeDealFetchResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): BaseResponsePageResponseTimeDealFetchResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'success': json['success'] == null ? undefined : json['success'],
        'code': json['code'] == null ? undefined : json['code'],
        'httpStatus': json['httpStatus'] == null ? undefined : json['httpStatus'],
        'message': json['message'] == null ? undefined : json['message'],
        'result': json['result'] == null ? undefined : PageResponseTimeDealFetchResponseFromJSON(json['result']),
    };
}

export function BaseResponsePageResponseTimeDealFetchResponseToJSON(json: any): BaseResponsePageResponseTimeDealFetchResponse {
    return BaseResponsePageResponseTimeDealFetchResponseToJSONTyped(json, false);
}

export function BaseResponsePageResponseTimeDealFetchResponseToJSONTyped(value?: BaseResponsePageResponseTimeDealFetchResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'success': value['success'],
        'code': value['code'],
        'httpStatus': value['httpStatus'],
        'message': value['message'],
        'result': PageResponseTimeDealFetchResponseToJSON(value['result']),
    };
}

