/* tslint:disable */
/* eslint-disable */
/**
 * zzirit API
 * 찌릿 API 명세서
 *
 * The version of the OpenAPI document: v0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PageResponseCurrentTimeDealFetchResponse } from './PageResponseCurrentTimeDealFetchResponse';
import {
    PageResponseCurrentTimeDealFetchResponseFromJSON,
    PageResponseCurrentTimeDealFetchResponseFromJSONTyped,
    PageResponseCurrentTimeDealFetchResponseToJSON,
    PageResponseCurrentTimeDealFetchResponseToJSONTyped,
} from './PageResponseCurrentTimeDealFetchResponse';

/**
 * 
 * @export
 * @interface BaseResponsePageResponseCurrentTimeDealFetchResponse
 */
export interface BaseResponsePageResponseCurrentTimeDealFetchResponse {
    /**
     * 
     * @type {boolean}
     * @memberof BaseResponsePageResponseCurrentTimeDealFetchResponse
     */
    success?: boolean;
    /**
     * 
     * @type {number}
     * @memberof BaseResponsePageResponseCurrentTimeDealFetchResponse
     */
    code?: number;
    /**
     * 
     * @type {number}
     * @memberof BaseResponsePageResponseCurrentTimeDealFetchResponse
     */
    httpStatus?: number;
    /**
     * 
     * @type {string}
     * @memberof BaseResponsePageResponseCurrentTimeDealFetchResponse
     */
    message?: string;
    /**
     * 
     * @type {PageResponseCurrentTimeDealFetchResponse}
     * @memberof BaseResponsePageResponseCurrentTimeDealFetchResponse
     */
    result?: PageResponseCurrentTimeDealFetchResponse;
}

/**
 * Check if a given object implements the BaseResponsePageResponseCurrentTimeDealFetchResponse interface.
 */
export function instanceOfBaseResponsePageResponseCurrentTimeDealFetchResponse(value: object): value is BaseResponsePageResponseCurrentTimeDealFetchResponse {
    return true;
}

export function BaseResponsePageResponseCurrentTimeDealFetchResponseFromJSON(json: any): BaseResponsePageResponseCurrentTimeDealFetchResponse {
    return BaseResponsePageResponseCurrentTimeDealFetchResponseFromJSONTyped(json, false);
}

export function BaseResponsePageResponseCurrentTimeDealFetchResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): BaseResponsePageResponseCurrentTimeDealFetchResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'success': json['success'] == null ? undefined : json['success'],
        'code': json['code'] == null ? undefined : json['code'],
        'httpStatus': json['httpStatus'] == null ? undefined : json['httpStatus'],
        'message': json['message'] == null ? undefined : json['message'],
        'result': json['result'] == null ? undefined : PageResponseCurrentTimeDealFetchResponseFromJSON(json['result']),
    };
}

export function BaseResponsePageResponseCurrentTimeDealFetchResponseToJSON(json: any): BaseResponsePageResponseCurrentTimeDealFetchResponse {
    return BaseResponsePageResponseCurrentTimeDealFetchResponseToJSONTyped(json, false);
}

export function BaseResponsePageResponseCurrentTimeDealFetchResponseToJSONTyped(value?: BaseResponsePageResponseCurrentTimeDealFetchResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'success': value['success'],
        'code': value['code'],
        'httpStatus': value['httpStatus'],
        'message': value['message'],
        'result': PageResponseCurrentTimeDealFetchResponseToJSON(value['result']),
    };
}

