/* tslint:disable */
/* eslint-disable */
/**
 * zzirit API
 * 찌릿 API 명세서
 *
 * The version of the OpenAPI document: v0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { TypeFetchResponse } from './TypeFetchResponse';
import {
    TypeFetchResponseFromJSON,
    TypeFetchResponseFromJSONTyped,
    TypeFetchResponseToJSON,
    TypeFetchResponseToJSONTyped,
} from './TypeFetchResponse';

/**
 * 
 * @export
 * @interface BaseResponseListTypeFetchResponse
 */
export interface BaseResponseListTypeFetchResponse {
    /**
     * 
     * @type {boolean}
     * @memberof BaseResponseListTypeFetchResponse
     */
    success?: boolean;
    /**
     * 
     * @type {number}
     * @memberof BaseResponseListTypeFetchResponse
     */
    code?: number;
    /**
     * 
     * @type {number}
     * @memberof BaseResponseListTypeFetchResponse
     */
    httpStatus?: number;
    /**
     * 
     * @type {string}
     * @memberof BaseResponseListTypeFetchResponse
     */
    message?: string;
    /**
     * 
     * @type {Array<TypeFetchResponse>}
     * @memberof BaseResponseListTypeFetchResponse
     */
    result?: Array<TypeFetchResponse>;
}

/**
 * Check if a given object implements the BaseResponseListTypeFetchResponse interface.
 */
export function instanceOfBaseResponseListTypeFetchResponse(value: object): value is BaseResponseListTypeFetchResponse {
    return true;
}

export function BaseResponseListTypeFetchResponseFromJSON(json: any): BaseResponseListTypeFetchResponse {
    return BaseResponseListTypeFetchResponseFromJSONTyped(json, false);
}

export function BaseResponseListTypeFetchResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): BaseResponseListTypeFetchResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'success': json['success'] == null ? undefined : json['success'],
        'code': json['code'] == null ? undefined : json['code'],
        'httpStatus': json['httpStatus'] == null ? undefined : json['httpStatus'],
        'message': json['message'] == null ? undefined : json['message'],
        'result': json['result'] == null ? undefined : ((json['result'] as Array<any>).map(TypeFetchResponseFromJSON)),
    };
}

export function BaseResponseListTypeFetchResponseToJSON(json: any): BaseResponseListTypeFetchResponse {
    return BaseResponseListTypeFetchResponseToJSONTyped(json, false);
}

export function BaseResponseListTypeFetchResponseToJSONTyped(value?: BaseResponseListTypeFetchResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'success': value['success'],
        'code': value['code'],
        'httpStatus': value['httpStatus'],
        'message': value['message'],
        'result': value['result'] == null ? undefined : ((value['result'] as Array<any>).map(TypeFetchResponseToJSON)),
    };
}

