/* tslint:disable */
/* eslint-disable */
/**
 * zzirit API
 * 찌릿 API 명세서
 *
 * The version of the OpenAPI document: v0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { TypeResponse } from './TypeResponse';
import {
    TypeResponseFromJSON,
    TypeResponseFromJSONTyped,
    TypeResponseToJSON,
    TypeResponseToJSONTyped,
} from './TypeResponse';

/**
 * 
 * @export
 * @interface BaseResponseListTypeResponse
 */
export interface BaseResponseListTypeResponse {
    /**
     * 
     * @type {boolean}
     * @memberof BaseResponseListTypeResponse
     */
    success?: boolean;
    /**
     * 
     * @type {number}
     * @memberof BaseResponseListTypeResponse
     */
    code?: number;
    /**
     * 
     * @type {number}
     * @memberof BaseResponseListTypeResponse
     */
    httpStatus?: number;
    /**
     * 
     * @type {string}
     * @memberof BaseResponseListTypeResponse
     */
    message?: string;
    /**
     * 
     * @type {Array<TypeResponse>}
     * @memberof BaseResponseListTypeResponse
     */
    result?: Array<TypeResponse>;
}

/**
 * Check if a given object implements the BaseResponseListTypeResponse interface.
 */
export function instanceOfBaseResponseListTypeResponse(value: object): value is BaseResponseListTypeResponse {
    return true;
}

export function BaseResponseListTypeResponseFromJSON(json: any): BaseResponseListTypeResponse {
    return BaseResponseListTypeResponseFromJSONTyped(json, false);
}

export function BaseResponseListTypeResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): BaseResponseListTypeResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'success': json['success'] == null ? undefined : json['success'],
        'code': json['code'] == null ? undefined : json['code'],
        'httpStatus': json['httpStatus'] == null ? undefined : json['httpStatus'],
        'message': json['message'] == null ? undefined : json['message'],
        'result': json['result'] == null ? undefined : ((json['result'] as Array<any>).map(TypeResponseFromJSON)),
    };
}

export function BaseResponseListTypeResponseToJSON(json: any): BaseResponseListTypeResponse {
    return BaseResponseListTypeResponseToJSONTyped(json, false);
}

export function BaseResponseListTypeResponseToJSONTyped(value?: BaseResponseListTypeResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'success': value['success'],
        'code': value['code'],
        'httpStatus': value['httpStatus'],
        'message': value['message'],
        'result': value['result'] == null ? undefined : ((value['result'] as Array<any>).map(TypeResponseToJSON)),
    };
}

