/* tslint:disable */
/* eslint-disable */
/**
 * zzirit API
 * 찌릿 API 명세서
 *
 * The version of the OpenAPI document: v0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PaymentConfirmResponse } from './PaymentConfirmResponse';
import {
    PaymentConfirmResponseFromJSON,
    PaymentConfirmResponseFromJSONTyped,
    PaymentConfirmResponseToJSON,
    PaymentConfirmResponseToJSONTyped,
} from './PaymentConfirmResponse';

/**
 * 
 * @export
 * @interface BaseResponsePaymentConfirmResponse
 */
export interface BaseResponsePaymentConfirmResponse {
    /**
     * 
     * @type {boolean}
     * @memberof BaseResponsePaymentConfirmResponse
     */
    success?: boolean;
    /**
     * 
     * @type {number}
     * @memberof BaseResponsePaymentConfirmResponse
     */
    code?: number;
    /**
     * 
     * @type {number}
     * @memberof BaseResponsePaymentConfirmResponse
     */
    httpStatus?: number;
    /**
     * 
     * @type {string}
     * @memberof BaseResponsePaymentConfirmResponse
     */
    message?: string;
    /**
     * 
     * @type {PaymentConfirmResponse}
     * @memberof BaseResponsePaymentConfirmResponse
     */
    result?: PaymentConfirmResponse;
}

/**
 * Check if a given object implements the BaseResponsePaymentConfirmResponse interface.
 */
export function instanceOfBaseResponsePaymentConfirmResponse(value: object): value is BaseResponsePaymentConfirmResponse {
    return true;
}

export function BaseResponsePaymentConfirmResponseFromJSON(json: any): BaseResponsePaymentConfirmResponse {
    return BaseResponsePaymentConfirmResponseFromJSONTyped(json, false);
}

export function BaseResponsePaymentConfirmResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): BaseResponsePaymentConfirmResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'success': json['success'] == null ? undefined : json['success'],
        'code': json['code'] == null ? undefined : json['code'],
        'httpStatus': json['httpStatus'] == null ? undefined : json['httpStatus'],
        'message': json['message'] == null ? undefined : json['message'],
        'result': json['result'] == null ? undefined : PaymentConfirmResponseFromJSON(json['result']),
    };
}

export function BaseResponsePaymentConfirmResponseToJSON(json: any): BaseResponsePaymentConfirmResponse {
    return BaseResponsePaymentConfirmResponseToJSONTyped(json, false);
}

export function BaseResponsePaymentConfirmResponseToJSONTyped(value?: BaseResponsePaymentConfirmResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'success': value['success'],
        'code': value['code'],
        'httpStatus': value['httpStatus'],
        'message': value['message'],
        'result': PaymentConfirmResponseToJSON(value['result']),
    };
}

