/* tslint:disable */
/* eslint-disable */
/**
 * zzirit API
 * 찌릿 API 명세서
 *
 * The version of the OpenAPI document: v0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { AdminItemResponse } from './AdminItemResponse';
import {
    AdminItemResponseFromJSON,
    AdminItemResponseFromJSONTyped,
    AdminItemResponseToJSON,
    AdminItemResponseToJSONTyped,
} from './AdminItemResponse';

/**
 * 
 * @export
 * @interface BaseResponseListAdminItemResponse
 */
export interface BaseResponseListAdminItemResponse {
    /**
     * 
     * @type {boolean}
     * @memberof BaseResponseListAdminItemResponse
     */
    success?: boolean;
    /**
     * 
     * @type {number}
     * @memberof BaseResponseListAdminItemResponse
     */
    code?: number;
    /**
     * 
     * @type {number}
     * @memberof BaseResponseListAdminItemResponse
     */
    httpStatus?: number;
    /**
     * 
     * @type {string}
     * @memberof BaseResponseListAdminItemResponse
     */
    message?: string;
    /**
     * 
     * @type {Array<AdminItemResponse>}
     * @memberof BaseResponseListAdminItemResponse
     */
    result?: Array<AdminItemResponse>;
}

/**
 * Check if a given object implements the BaseResponseListAdminItemResponse interface.
 */
export function instanceOfBaseResponseListAdminItemResponse(value: object): value is BaseResponseListAdminItemResponse {
    return true;
}

export function BaseResponseListAdminItemResponseFromJSON(json: any): BaseResponseListAdminItemResponse {
    return BaseResponseListAdminItemResponseFromJSONTyped(json, false);
}

export function BaseResponseListAdminItemResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): BaseResponseListAdminItemResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'success': json['success'] == null ? undefined : json['success'],
        'code': json['code'] == null ? undefined : json['code'],
        'httpStatus': json['httpStatus'] == null ? undefined : json['httpStatus'],
        'message': json['message'] == null ? undefined : json['message'],
        'result': json['result'] == null ? undefined : ((json['result'] as Array<any>).map(AdminItemResponseFromJSON)),
    };
}

export function BaseResponseListAdminItemResponseToJSON(json: any): BaseResponseListAdminItemResponse {
    return BaseResponseListAdminItemResponseToJSONTyped(json, false);
}

export function BaseResponseListAdminItemResponseToJSONTyped(value?: BaseResponseListAdminItemResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'success': value['success'],
        'code': value['code'],
        'httpStatus': value['httpStatus'],
        'message': value['message'],
        'result': value['result'] == null ? undefined : ((value['result'] as Array<any>).map(AdminItemResponseToJSON)),
    };
}

