/* tslint:disable */
/* eslint-disable */
/**
 * zzirit API
 * 찌릿 API 명세서
 *
 * The version of the OpenAPI document: v0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PaymentInitResponse } from './PaymentInitResponse';
import {
    PaymentInitResponseFromJSON,
    PaymentInitResponseFromJSONTyped,
    PaymentInitResponseToJSON,
    PaymentInitResponseToJSONTyped,
} from './PaymentInitResponse';

/**
 * 
 * @export
 * @interface BaseResponsePaymentInitResponse
 */
export interface BaseResponsePaymentInitResponse {
    /**
     * 
     * @type {boolean}
     * @memberof BaseResponsePaymentInitResponse
     */
    success?: boolean;
    /**
     * 
     * @type {number}
     * @memberof BaseResponsePaymentInitResponse
     */
    code?: number;
    /**
     * 
     * @type {number}
     * @memberof BaseResponsePaymentInitResponse
     */
    httpStatus?: number;
    /**
     * 
     * @type {string}
     * @memberof BaseResponsePaymentInitResponse
     */
    message?: string;
    /**
     * 
     * @type {PaymentInitResponse}
     * @memberof BaseResponsePaymentInitResponse
     */
    result?: PaymentInitResponse;
}

/**
 * Check if a given object implements the BaseResponsePaymentInitResponse interface.
 */
export function instanceOfBaseResponsePaymentInitResponse(value: object): value is BaseResponsePaymentInitResponse {
    return true;
}

export function BaseResponsePaymentInitResponseFromJSON(json: any): BaseResponsePaymentInitResponse {
    return BaseResponsePaymentInitResponseFromJSONTyped(json, false);
}

export function BaseResponsePaymentInitResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): BaseResponsePaymentInitResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'success': json['success'] == null ? undefined : json['success'],
        'code': json['code'] == null ? undefined : json['code'],
        'httpStatus': json['httpStatus'] == null ? undefined : json['httpStatus'],
        'message': json['message'] == null ? undefined : json['message'],
        'result': json['result'] == null ? undefined : PaymentInitResponseFromJSON(json['result']),
    };
}

export function BaseResponsePaymentInitResponseToJSON(json: any): BaseResponsePaymentInitResponse {
    return BaseResponsePaymentInitResponseToJSONTyped(json, false);
}

export function BaseResponsePaymentInitResponseToJSONTyped(value?: BaseResponsePaymentInitResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'success': value['success'],
        'code': value['code'],
        'httpStatus': value['httpStatus'],
        'message': value['message'],
        'result': PaymentInitResponseToJSON(value['result']),
    };
}

