/* tslint:disable */
/* eslint-disable */
/**
 * zzirit API
 * 찌릿 API 명세서
 *
 * The version of the OpenAPI document: v0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { SimpleItemResponse } from './SimpleItemResponse';
import {
    SimpleItemResponseFromJSON,
    SimpleItemResponseFromJSONTyped,
    SimpleItemResponseToJSON,
    SimpleItemResponseToJSONTyped,
} from './SimpleItemResponse';

/**
 * 
 * @export
 * @interface BaseResponseListSimpleItemResponse
 */
export interface BaseResponseListSimpleItemResponse {
    /**
     * 
     * @type {boolean}
     * @memberof BaseResponseListSimpleItemResponse
     */
    success?: boolean;
    /**
     * 
     * @type {number}
     * @memberof BaseResponseListSimpleItemResponse
     */
    code?: number;
    /**
     * 
     * @type {number}
     * @memberof BaseResponseListSimpleItemResponse
     */
    httpStatus?: number;
    /**
     * 
     * @type {string}
     * @memberof BaseResponseListSimpleItemResponse
     */
    message?: string;
    /**
     * 
     * @type {Array<SimpleItemResponse>}
     * @memberof BaseResponseListSimpleItemResponse
     */
    result?: Array<SimpleItemResponse>;
}

/**
 * Check if a given object implements the BaseResponseListSimpleItemResponse interface.
 */
export function instanceOfBaseResponseListSimpleItemResponse(value: object): value is BaseResponseListSimpleItemResponse {
    return true;
}

export function BaseResponseListSimpleItemResponseFromJSON(json: any): BaseResponseListSimpleItemResponse {
    return BaseResponseListSimpleItemResponseFromJSONTyped(json, false);
}

export function BaseResponseListSimpleItemResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): BaseResponseListSimpleItemResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'success': json['success'] == null ? undefined : json['success'],
        'code': json['code'] == null ? undefined : json['code'],
        'httpStatus': json['httpStatus'] == null ? undefined : json['httpStatus'],
        'message': json['message'] == null ? undefined : json['message'],
        'result': json['result'] == null ? undefined : ((json['result'] as Array<any>).map(SimpleItemResponseFromJSON)),
    };
}

export function BaseResponseListSimpleItemResponseToJSON(json: any): BaseResponseListSimpleItemResponse {
    return BaseResponseListSimpleItemResponseToJSONTyped(json, false);
}

export function BaseResponseListSimpleItemResponseToJSONTyped(value?: BaseResponseListSimpleItemResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'success': value['success'],
        'code': value['code'],
        'httpStatus': value['httpStatus'],
        'message': value['message'],
        'result': value['result'] == null ? undefined : ((value['result'] as Array<any>).map(SimpleItemResponseToJSON)),
    };
}

