/* tslint:disable */
/* eslint-disable */
/**
 * zzirit API
 * 찌릿 API 명세서
 *
 * The version of the OpenAPI document: v0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PageResponseSimpleItemFetchResponse } from './PageResponseSimpleItemFetchResponse';
import {
    PageResponseSimpleItemFetchResponseFromJSON,
    PageResponseSimpleItemFetchResponseFromJSONTyped,
    PageResponseSimpleItemFetchResponseToJSON,
    PageResponseSimpleItemFetchResponseToJSONTyped,
} from './PageResponseSimpleItemFetchResponse';

/**
 * 
 * @export
 * @interface BaseResponsePageResponseSimpleItemFetchResponse
 */
export interface BaseResponsePageResponseSimpleItemFetchResponse {
    /**
     * 
     * @type {boolean}
     * @memberof BaseResponsePageResponseSimpleItemFetchResponse
     */
    success?: boolean;
    /**
     * 
     * @type {number}
     * @memberof BaseResponsePageResponseSimpleItemFetchResponse
     */
    code?: number;
    /**
     * 
     * @type {number}
     * @memberof BaseResponsePageResponseSimpleItemFetchResponse
     */
    httpStatus?: number;
    /**
     * 
     * @type {string}
     * @memberof BaseResponsePageResponseSimpleItemFetchResponse
     */
    message?: string;
    /**
     * 
     * @type {PageResponseSimpleItemFetchResponse}
     * @memberof BaseResponsePageResponseSimpleItemFetchResponse
     */
    result?: PageResponseSimpleItemFetchResponse;
}

/**
 * Check if a given object implements the BaseResponsePageResponseSimpleItemFetchResponse interface.
 */
export function instanceOfBaseResponsePageResponseSimpleItemFetchResponse(value: object): value is BaseResponsePageResponseSimpleItemFetchResponse {
    return true;
}

export function BaseResponsePageResponseSimpleItemFetchResponseFromJSON(json: any): BaseResponsePageResponseSimpleItemFetchResponse {
    return BaseResponsePageResponseSimpleItemFetchResponseFromJSONTyped(json, false);
}

export function BaseResponsePageResponseSimpleItemFetchResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): BaseResponsePageResponseSimpleItemFetchResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'success': json['success'] == null ? undefined : json['success'],
        'code': json['code'] == null ? undefined : json['code'],
        'httpStatus': json['httpStatus'] == null ? undefined : json['httpStatus'],
        'message': json['message'] == null ? undefined : json['message'],
        'result': json['result'] == null ? undefined : PageResponseSimpleItemFetchResponseFromJSON(json['result']),
    };
}

export function BaseResponsePageResponseSimpleItemFetchResponseToJSON(json: any): BaseResponsePageResponseSimpleItemFetchResponse {
    return BaseResponsePageResponseSimpleItemFetchResponseToJSONTyped(json, false);
}

export function BaseResponsePageResponseSimpleItemFetchResponseToJSONTyped(value?: BaseResponsePageResponseSimpleItemFetchResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'success': value['success'],
        'code': value['code'],
        'httpStatus': value['httpStatus'],
        'message': value['message'],
        'result': PageResponseSimpleItemFetchResponseToJSON(value['result']),
    };
}

