/* tslint:disable */
/* eslint-disable */
/**
 * zzirit API
 * 찌릿 API 명세서
 *
 * The version of the OpenAPI document: v0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PageResponseItemFetchQueryResponse } from './PageResponseItemFetchQueryResponse';
import {
    PageResponseItemFetchQueryResponseFromJSON,
    PageResponseItemFetchQueryResponseFromJSONTyped,
    PageResponseItemFetchQueryResponseToJSON,
    PageResponseItemFetchQueryResponseToJSONTyped,
} from './PageResponseItemFetchQueryResponse';

/**
 * 
 * @export
 * @interface BaseResponsePageResponseItemFetchQueryResponse
 */
export interface BaseResponsePageResponseItemFetchQueryResponse {
    /**
     * 
     * @type {boolean}
     * @memberof BaseResponsePageResponseItemFetchQueryResponse
     */
    success?: boolean;
    /**
     * 
     * @type {number}
     * @memberof BaseResponsePageResponseItemFetchQueryResponse
     */
    code?: number;
    /**
     * 
     * @type {number}
     * @memberof BaseResponsePageResponseItemFetchQueryResponse
     */
    httpStatus?: number;
    /**
     * 
     * @type {string}
     * @memberof BaseResponsePageResponseItemFetchQueryResponse
     */
    message?: string;
    /**
     * 
     * @type {PageResponseItemFetchQueryResponse}
     * @memberof BaseResponsePageResponseItemFetchQueryResponse
     */
    result?: PageResponseItemFetchQueryResponse;
}

/**
 * Check if a given object implements the BaseResponsePageResponseItemFetchQueryResponse interface.
 */
export function instanceOfBaseResponsePageResponseItemFetchQueryResponse(value: object): value is BaseResponsePageResponseItemFetchQueryResponse {
    return true;
}

export function BaseResponsePageResponseItemFetchQueryResponseFromJSON(json: any): BaseResponsePageResponseItemFetchQueryResponse {
    return BaseResponsePageResponseItemFetchQueryResponseFromJSONTyped(json, false);
}

export function BaseResponsePageResponseItemFetchQueryResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): BaseResponsePageResponseItemFetchQueryResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'success': json['success'] == null ? undefined : json['success'],
        'code': json['code'] == null ? undefined : json['code'],
        'httpStatus': json['httpStatus'] == null ? undefined : json['httpStatus'],
        'message': json['message'] == null ? undefined : json['message'],
        'result': json['result'] == null ? undefined : PageResponseItemFetchQueryResponseFromJSON(json['result']),
    };
}

export function BaseResponsePageResponseItemFetchQueryResponseToJSON(json: any): BaseResponsePageResponseItemFetchQueryResponse {
    return BaseResponsePageResponseItemFetchQueryResponseToJSONTyped(json, false);
}

export function BaseResponsePageResponseItemFetchQueryResponseToJSONTyped(value?: BaseResponsePageResponseItemFetchQueryResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'success': value['success'],
        'code': value['code'],
        'httpStatus': value['httpStatus'],
        'message': value['message'],
        'result': PageResponseItemFetchQueryResponseToJSON(value['result']),
    };
}

