/* tslint:disable */
/* eslint-disable */
/**
 * zzirit API
 * 찌릿 API 명세서
 *
 * The version of the OpenAPI document: v0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { BrandResponse } from './BrandResponse';
import {
    BrandResponseFromJSON,
    BrandResponseFromJSONTyped,
    BrandResponseToJSON,
    BrandResponseToJSONTyped,
} from './BrandResponse';

/**
 * 
 * @export
 * @interface BaseResponseListBrandResponse
 */
export interface BaseResponseListBrandResponse {
    /**
     * 
     * @type {boolean}
     * @memberof BaseResponseListBrandResponse
     */
    success?: boolean;
    /**
     * 
     * @type {number}
     * @memberof BaseResponseListBrandResponse
     */
    code?: number;
    /**
     * 
     * @type {number}
     * @memberof BaseResponseListBrandResponse
     */
    httpStatus?: number;
    /**
     * 
     * @type {string}
     * @memberof BaseResponseListBrandResponse
     */
    message?: string;
    /**
     * 
     * @type {Array<BrandResponse>}
     * @memberof BaseResponseListBrandResponse
     */
    result?: Array<BrandResponse>;
}

/**
 * Check if a given object implements the BaseResponseListBrandResponse interface.
 */
export function instanceOfBaseResponseListBrandResponse(value: object): value is BaseResponseListBrandResponse {
    return true;
}

export function BaseResponseListBrandResponseFromJSON(json: any): BaseResponseListBrandResponse {
    return BaseResponseListBrandResponseFromJSONTyped(json, false);
}

export function BaseResponseListBrandResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): BaseResponseListBrandResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'success': json['success'] == null ? undefined : json['success'],
        'code': json['code'] == null ? undefined : json['code'],
        'httpStatus': json['httpStatus'] == null ? undefined : json['httpStatus'],
        'message': json['message'] == null ? undefined : json['message'],
        'result': json['result'] == null ? undefined : ((json['result'] as Array<any>).map(BrandResponseFromJSON)),
    };
}

export function BaseResponseListBrandResponseToJSON(json: any): BaseResponseListBrandResponse {
    return BaseResponseListBrandResponseToJSONTyped(json, false);
}

export function BaseResponseListBrandResponseToJSONTyped(value?: BaseResponseListBrandResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'success': value['success'],
        'code': value['code'],
        'httpStatus': value['httpStatus'],
        'message': value['message'],
        'result': value['result'] == null ? undefined : ((value['result'] as Array<any>).map(BrandResponseToJSON)),
    };
}

