/* tslint:disable */
/* eslint-disable */
/**
 * zzirit API
 * 찌릿 API 명세서
 *
 * The version of the OpenAPI document: v0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { BrandFetchResponse } from './BrandFetchResponse';
import {
    BrandFetchResponseFromJSON,
    BrandFetchResponseFromJSONTyped,
    BrandFetchResponseToJSON,
    BrandFetchResponseToJSONTyped,
} from './BrandFetchResponse';

/**
 * 
 * @export
 * @interface BaseResponseListBrandFetchResponse
 */
export interface BaseResponseListBrandFetchResponse {
    /**
     * 
     * @type {boolean}
     * @memberof BaseResponseListBrandFetchResponse
     */
    success?: boolean;
    /**
     * 
     * @type {number}
     * @memberof BaseResponseListBrandFetchResponse
     */
    code?: number;
    /**
     * 
     * @type {number}
     * @memberof BaseResponseListBrandFetchResponse
     */
    httpStatus?: number;
    /**
     * 
     * @type {string}
     * @memberof BaseResponseListBrandFetchResponse
     */
    message?: string;
    /**
     * 
     * @type {Array<BrandFetchResponse>}
     * @memberof BaseResponseListBrandFetchResponse
     */
    result?: Array<BrandFetchResponse>;
}

/**
 * Check if a given object implements the BaseResponseListBrandFetchResponse interface.
 */
export function instanceOfBaseResponseListBrandFetchResponse(value: object): value is BaseResponseListBrandFetchResponse {
    return true;
}

export function BaseResponseListBrandFetchResponseFromJSON(json: any): BaseResponseListBrandFetchResponse {
    return BaseResponseListBrandFetchResponseFromJSONTyped(json, false);
}

export function BaseResponseListBrandFetchResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): BaseResponseListBrandFetchResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'success': json['success'] == null ? undefined : json['success'],
        'code': json['code'] == null ? undefined : json['code'],
        'httpStatus': json['httpStatus'] == null ? undefined : json['httpStatus'],
        'message': json['message'] == null ? undefined : json['message'],
        'result': json['result'] == null ? undefined : ((json['result'] as Array<any>).map(BrandFetchResponseFromJSON)),
    };
}

export function BaseResponseListBrandFetchResponseToJSON(json: any): BaseResponseListBrandFetchResponse {
    return BaseResponseListBrandFetchResponseToJSONTyped(json, false);
}

export function BaseResponseListBrandFetchResponseToJSONTyped(value?: BaseResponseListBrandFetchResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'success': value['success'],
        'code': value['code'],
        'httpStatus': value['httpStatus'],
        'message': value['message'],
        'result': value['result'] == null ? undefined : ((value['result'] as Array<any>).map(BrandFetchResponseToJSON)),
    };
}

