/* tslint:disable */
/* eslint-disable */
/**
 * zzirit API
 * 찌릿 API 명세서
 *
 * The version of the OpenAPI document: v0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface BaseResponseString
 */
export interface BaseResponseString {
    /**
     * 
     * @type {boolean}
     * @memberof BaseResponseString
     */
    success?: boolean;
    /**
     * 
     * @type {number}
     * @memberof BaseResponseString
     */
    code?: number;
    /**
     * 
     * @type {number}
     * @memberof BaseResponseString
     */
    httpStatus?: number;
    /**
     * 
     * @type {string}
     * @memberof BaseResponseString
     */
    message?: string;
    /**
     * 
     * @type {string}
     * @memberof BaseResponseString
     */
    result?: string;
}

/**
 * Check if a given object implements the BaseResponseString interface.
 */
export function instanceOfBaseResponseString(value: object): value is BaseResponseString {
    return true;
}

export function BaseResponseStringFromJSON(json: any): BaseResponseString {
    return BaseResponseStringFromJSONTyped(json, false);
}

export function BaseResponseStringFromJSONTyped(json: any, ignoreDiscriminator: boolean): BaseResponseString {
    if (json == null) {
        return json;
    }
    return {
        
        'success': json['success'] == null ? undefined : json['success'],
        'code': json['code'] == null ? undefined : json['code'],
        'httpStatus': json['httpStatus'] == null ? undefined : json['httpStatus'],
        'message': json['message'] == null ? undefined : json['message'],
        'result': json['result'] == null ? undefined : json['result'],
    };
}

export function BaseResponseStringToJSON(json: any): BaseResponseString {
    return BaseResponseStringToJSONTyped(json, false);
}

export function BaseResponseStringToJSONTyped(value?: BaseResponseString | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'success': value['success'],
        'code': value['code'],
        'httpStatus': value['httpStatus'],
        'message': value['message'],
        'result': value['result'],
    };
}

