/* tslint:disable */
/* eslint-disable */
/**
 * zzirit API
 * 찌릿 API 명세서
 *
 * The version of the OpenAPI document: v0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ItemResponse } from './ItemResponse';
import {
    ItemResponseFromJSON,
    ItemResponseFromJSONTyped,
    ItemResponseToJSON,
    ItemResponseToJSONTyped,
} from './ItemResponse';

/**
 * 
 * @export
 * @interface BaseResponseItemResponse
 */
export interface BaseResponseItemResponse {
    /**
     * 
     * @type {boolean}
     * @memberof BaseResponseItemResponse
     */
    success?: boolean;
    /**
     * 
     * @type {number}
     * @memberof BaseResponseItemResponse
     */
    code?: number;
    /**
     * 
     * @type {number}
     * @memberof BaseResponseItemResponse
     */
    httpStatus?: number;
    /**
     * 
     * @type {string}
     * @memberof BaseResponseItemResponse
     */
    message?: string;
    /**
     * 
     * @type {ItemResponse}
     * @memberof BaseResponseItemResponse
     */
    result?: ItemResponse;
}

/**
 * Check if a given object implements the BaseResponseItemResponse interface.
 */
export function instanceOfBaseResponseItemResponse(value: object): value is BaseResponseItemResponse {
    return true;
}

export function BaseResponseItemResponseFromJSON(json: any): BaseResponseItemResponse {
    return BaseResponseItemResponseFromJSONTyped(json, false);
}

export function BaseResponseItemResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): BaseResponseItemResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'success': json['success'] == null ? undefined : json['success'],
        'code': json['code'] == null ? undefined : json['code'],
        'httpStatus': json['httpStatus'] == null ? undefined : json['httpStatus'],
        'message': json['message'] == null ? undefined : json['message'],
        'result': json['result'] == null ? undefined : ItemResponseFromJSON(json['result']),
    };
}

export function BaseResponseItemResponseToJSON(json: any): BaseResponseItemResponse {
    return BaseResponseItemResponseToJSONTyped(json, false);
}

export function BaseResponseItemResponseToJSONTyped(value?: BaseResponseItemResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'success': value['success'],
        'code': value['code'],
        'httpStatus': value['httpStatus'],
        'message': value['message'],
        'result': ItemResponseToJSON(value['result']),
    };
}

