/* tslint:disable */
/* eslint-disable */
/**
 * zzirit API
 * 찌릿 API 명세서
 *
 * The version of the OpenAPI document: v0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ImageUploadResponse } from './ImageUploadResponse';
import {
    ImageUploadResponseFromJSON,
    ImageUploadResponseFromJSONTyped,
    ImageUploadResponseToJSON,
    ImageUploadResponseToJSONTyped,
} from './ImageUploadResponse';

/**
 * 
 * @export
 * @interface BaseResponseImageUploadResponse
 */
export interface BaseResponseImageUploadResponse {
    /**
     * 
     * @type {boolean}
     * @memberof BaseResponseImageUploadResponse
     */
    success?: boolean;
    /**
     * 
     * @type {number}
     * @memberof BaseResponseImageUploadResponse
     */
    code?: number;
    /**
     * 
     * @type {number}
     * @memberof BaseResponseImageUploadResponse
     */
    httpStatus?: number;
    /**
     * 
     * @type {string}
     * @memberof BaseResponseImageUploadResponse
     */
    message?: string;
    /**
     * 
     * @type {ImageUploadResponse}
     * @memberof BaseResponseImageUploadResponse
     */
    result?: ImageUploadResponse;
}

/**
 * Check if a given object implements the BaseResponseImageUploadResponse interface.
 */
export function instanceOfBaseResponseImageUploadResponse(value: object): value is BaseResponseImageUploadResponse {
    return true;
}

export function BaseResponseImageUploadResponseFromJSON(json: any): BaseResponseImageUploadResponse {
    return BaseResponseImageUploadResponseFromJSONTyped(json, false);
}

export function BaseResponseImageUploadResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): BaseResponseImageUploadResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'success': json['success'] == null ? undefined : json['success'],
        'code': json['code'] == null ? undefined : json['code'],
        'httpStatus': json['httpStatus'] == null ? undefined : json['httpStatus'],
        'message': json['message'] == null ? undefined : json['message'],
        'result': json['result'] == null ? undefined : ImageUploadResponseFromJSON(json['result']),
    };
}

export function BaseResponseImageUploadResponseToJSON(json: any): BaseResponseImageUploadResponse {
    return BaseResponseImageUploadResponseToJSONTyped(json, false);
}

export function BaseResponseImageUploadResponseToJSONTyped(value?: BaseResponseImageUploadResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'success': value['success'],
        'code': value['code'],
        'httpStatus': value['httpStatus'],
        'message': value['message'],
        'result': ImageUploadResponseToJSON(value['result']),
    };
}

