/* tslint:disable */
/* eslint-disable */
/**
 * zzirit API
 * 찌릿 API 명세서
 *
 * The version of the OpenAPI document: v0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface BrandResponse
 */
export interface BrandResponse {
    /**
     * 
     * @type {number}
     * @memberof BrandResponse
     */
    brandId?: number;
    /**
     * 
     * @type {string}
     * @memberof BrandResponse
     */
    name?: string;
}

/**
 * Check if a given object implements the BrandResponse interface.
 */
export function instanceOfBrandResponse(value: object): value is BrandResponse {
    return true;
}

export function BrandResponseFromJSON(json: any): BrandResponse {
    return BrandResponseFromJSONTyped(json, false);
}

export function BrandResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): BrandResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'brandId': json['brandId'] == null ? undefined : json['brandId'],
        'name': json['name'] == null ? undefined : json['name'],
    };
}

export function BrandResponseToJSON(json: any): BrandResponse {
    return BrandResponseToJSONTyped(json, false);
}

export function BrandResponseToJSONTyped(value?: BrandResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'brandId': value['brandId'],
        'name': value['name'],
    };
}

