/* tslint:disable */
/* eslint-disable */
/**
 * zzirit API
 * 찌릿 API 명세서
 *
 * The version of the OpenAPI document: v0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 장바구니 상품 추가 요청 DTO
 * @export
 * @interface CartItemCreateRequest
 */
export interface CartItemCreateRequest {
    /**
     * 
     * @type {number}
     * @memberof CartItemCreateRequest
     */
    itemId?: number;
    /**
     * 
     * @type {number}
     * @memberof CartItemCreateRequest
     */
    quantity?: number;
}

/**
 * Check if a given object implements the CartItemCreateRequest interface.
 */
export function instanceOfCartItemCreateRequest(value: object): value is CartItemCreateRequest {
    return true;
}

export function CartItemCreateRequestFromJSON(json: any): CartItemCreateRequest {
    return CartItemCreateRequestFromJSONTyped(json, false);
}

export function CartItemCreateRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CartItemCreateRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'itemId': json['itemId'] == null ? undefined : json['itemId'],
        'quantity': json['quantity'] == null ? undefined : json['quantity'],
    };
}

export function CartItemCreateRequestToJSON(json: any): CartItemCreateRequest {
    return CartItemCreateRequestToJSONTyped(json, false);
}

export function CartItemCreateRequestToJSONTyped(value?: CartItemCreateRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'itemId': value['itemId'],
        'quantity': value['quantity'],
    };
}

