/* tslint:disable */
/* eslint-disable */
/**
 * zzirit API
 * 찌릿 API 명세서
 *
 * The version of the OpenAPI document: v0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 장바구니 선택 삭제 요청 DTO
 * @export
 * @interface CartItemDeleteRequest
 */
export interface CartItemDeleteRequest {
    /**
     * 
     * @type {Array<number>}
     * @memberof CartItemDeleteRequest
     */
    itemIds?: Array<number>;
}

/**
 * Check if a given object implements the CartItemDeleteRequest interface.
 */
export function instanceOfCartItemDeleteRequest(value: object): value is CartItemDeleteRequest {
    return true;
}

export function CartItemDeleteRequestFromJSON(json: any): CartItemDeleteRequest {
    return CartItemDeleteRequestFromJSONTyped(json, false);
}

export function CartItemDeleteRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CartItemDeleteRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'itemIds': json['itemIds'] == null ? undefined : json['itemIds'],
    };
}

export function CartItemDeleteRequestToJSON(json: any): CartItemDeleteRequest {
    return CartItemDeleteRequestToJSONTyped(json, false);
}

export function CartItemDeleteRequestToJSONTyped(value?: CartItemDeleteRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'itemIds': value['itemIds'],
    };
}

