/* tslint:disable */
/* eslint-disable */
/**
 * zzirit API
 * 찌릿 API 명세서
 *
 * The version of the OpenAPI document: v0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { CartItemFetchResponse } from './CartItemFetchResponse';
import {
    CartItemFetchResponseFromJSON,
    CartItemFetchResponseFromJSONTyped,
    CartItemFetchResponseToJSON,
    CartItemFetchResponseToJSONTyped,
} from './CartItemFetchResponse';

/**
 * 장바구니 응답 DTO
 * @export
 * @interface CartFetchResponse
 */
export interface CartFetchResponse {
    /**
     * 
     * @type {number}
     * @memberof CartFetchResponse
     */
    cartId?: number;
    /**
     * 
     * @type {Array<CartItemFetchResponse>}
     * @memberof CartFetchResponse
     */
    items?: Array<CartItemFetchResponse>;
    /**
     * 
     * @type {number}
     * @memberof CartFetchResponse
     */
    cartTotalQuantity?: number;
    /**
     * 
     * @type {number}
     * @memberof CartFetchResponse
     */
    cartTotalPrice?: number;
}

/**
 * Check if a given object implements the CartFetchResponse interface.
 */
export function instanceOfCartFetchResponse(value: object): value is CartFetchResponse {
    return true;
}

export function CartFetchResponseFromJSON(json: any): CartFetchResponse {
    return CartFetchResponseFromJSONTyped(json, false);
}

export function CartFetchResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): CartFetchResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'cartId': json['cartId'] == null ? undefined : json['cartId'],
        'items': json['items'] == null ? undefined : ((json['items'] as Array<any>).map(CartItemFetchResponseFromJSON)),
        'cartTotalQuantity': json['cartTotalQuantity'] == null ? undefined : json['cartTotalQuantity'],
        'cartTotalPrice': json['cartTotalPrice'] == null ? undefined : json['cartTotalPrice'],
    };
}

export function CartFetchResponseToJSON(json: any): CartFetchResponse {
    return CartFetchResponseToJSONTyped(json, false);
}

export function CartFetchResponseToJSONTyped(value?: CartFetchResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'cartId': value['cartId'],
        'items': value['items'] == null ? undefined : ((value['items'] as Array<any>).map(CartItemFetchResponseToJSON)),
        'cartTotalQuantity': value['cartTotalQuantity'],
        'cartTotalPrice': value['cartTotalPrice'],
    };
}

