/* tslint:disable */
/* eslint-disable */
/**
 * zzirit API
 * 찌릿 API 명세서
 *
 * The version of the OpenAPI document: v0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 장바구니 상품 응답 DTO
 * @export
 * @interface CartItemFetchResponse
 */
export interface CartItemFetchResponse {
    /**
     * 
     * @type {number}
     * @memberof CartItemFetchResponse
     */
    cartItemId?: number;
    /**
     * 
     * @type {number}
     * @memberof CartItemFetchResponse
     */
    itemId?: number;
    /**
     * 
     * @type {string}
     * @memberof CartItemFetchResponse
     */
    itemName?: string;
    /**
     * 
     * @type {string}
     * @memberof CartItemFetchResponse
     */
    type?: string;
    /**
     * 
     * @type {string}
     * @memberof CartItemFetchResponse
     */
    brand?: string;
    /**
     * 
     * @type {number}
     * @memberof CartItemFetchResponse
     */
    quantity?: number;
    /**
     * 
     * @type {string}
     * @memberof CartItemFetchResponse
     */
    imageUrl?: string;
    /**
     * 
     * @type {number}
     * @memberof CartItemFetchResponse
     */
    originalPrice?: number;
    /**
     * 
     * @type {number}
     * @memberof CartItemFetchResponse
     */
    discountedPrice?: number;
    /**
     * 
     * @type {number}
     * @memberof CartItemFetchResponse
     */
    totalPrice?: number;
    /**
     * 
     * @type {boolean}
     * @memberof CartItemFetchResponse
     */
    isTimeDeal?: boolean;
    /**
     * 
     * @type {number}
     * @memberof CartItemFetchResponse
     */
    discountRatio?: number;
    /**
     * 
     * @type {boolean}
     * @memberof CartItemFetchResponse
     */
    isSoldOut?: boolean;
}

/**
 * Check if a given object implements the CartItemFetchResponse interface.
 */
export function instanceOfCartItemFetchResponse(value: object): value is CartItemFetchResponse {
    return true;
}

export function CartItemFetchResponseFromJSON(json: any): CartItemFetchResponse {
    return CartItemFetchResponseFromJSONTyped(json, false);
}

export function CartItemFetchResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): CartItemFetchResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'cartItemId': json['cartItemId'] == null ? undefined : json['cartItemId'],
        'itemId': json['itemId'] == null ? undefined : json['itemId'],
        'itemName': json['itemName'] == null ? undefined : json['itemName'],
        'type': json['type'] == null ? undefined : json['type'],
        'brand': json['brand'] == null ? undefined : json['brand'],
        'quantity': json['quantity'] == null ? undefined : json['quantity'],
        'imageUrl': json['imageUrl'] == null ? undefined : json['imageUrl'],
        'originalPrice': json['originalPrice'] == null ? undefined : json['originalPrice'],
        'discountedPrice': json['discountedPrice'] == null ? undefined : json['discountedPrice'],
        'totalPrice': json['totalPrice'] == null ? undefined : json['totalPrice'],
        'isTimeDeal': json['isTimeDeal'] == null ? undefined : json['isTimeDeal'],
        'discountRatio': json['discountRatio'] == null ? undefined : json['discountRatio'],
        'isSoldOut': json['isSoldOut'] == null ? undefined : json['isSoldOut'],
    };
}

export function CartItemFetchResponseToJSON(json: any): CartItemFetchResponse {
    return CartItemFetchResponseToJSONTyped(json, false);
}

export function CartItemFetchResponseToJSONTyped(value?: CartItemFetchResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'cartItemId': value['cartItemId'],
        'itemId': value['itemId'],
        'itemName': value['itemName'],
        'type': value['type'],
        'brand': value['brand'],
        'quantity': value['quantity'],
        'imageUrl': value['imageUrl'],
        'originalPrice': value['originalPrice'],
        'discountedPrice': value['discountedPrice'],
        'totalPrice': value['totalPrice'],
        'isTimeDeal': value['isTimeDeal'],
        'discountRatio': value['discountRatio'],
        'isSoldOut': value['isSoldOut'],
    };
}

