/* tslint:disable */
/* eslint-disable */
/**
 * zzirit API
 * 찌릿 API 명세서
 *
 * The version of the OpenAPI document: v0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CartItemResponse
 */
export interface CartItemResponse {
    /**
     * 
     * @type {number}
     * @memberof CartItemResponse
     */
    cartItemId?: number;
    /**
     * 
     * @type {number}
     * @memberof CartItemResponse
     */
    itemId?: number;
    /**
     * 
     * @type {string}
     * @memberof CartItemResponse
     */
    itemName?: string;
    /**
     * 
     * @type {string}
     * @memberof CartItemResponse
     */
    itemImageUrl?: string;
    /**
     * 
     * @type {number}
     * @memberof CartItemResponse
     */
    quantity?: number;
    /**
     * 
     * @type {number}
     * @memberof CartItemResponse
     */
    unitPrice?: number;
    /**
     * 
     * @type {number}
     * @memberof CartItemResponse
     */
    totalPrice?: number;
    /**
     * 
     * @type {number}
     * @memberof CartItemResponse
     */
    discountRatio?: number;
    /**
     * 
     * @type {boolean}
     * @memberof CartItemResponse
     */
    timeDeal?: boolean;
}

/**
 * Check if a given object implements the CartItemResponse interface.
 */
export function instanceOfCartItemResponse(value: object): value is CartItemResponse {
    return true;
}

export function CartItemResponseFromJSON(json: any): CartItemResponse {
    return CartItemResponseFromJSONTyped(json, false);
}

export function CartItemResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): CartItemResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'cartItemId': json['cartItemId'] == null ? undefined : json['cartItemId'],
        'itemId': json['itemId'] == null ? undefined : json['itemId'],
        'itemName': json['itemName'] == null ? undefined : json['itemName'],
        'itemImageUrl': json['itemImageUrl'] == null ? undefined : json['itemImageUrl'],
        'quantity': json['quantity'] == null ? undefined : json['quantity'],
        'unitPrice': json['unitPrice'] == null ? undefined : json['unitPrice'],
        'totalPrice': json['totalPrice'] == null ? undefined : json['totalPrice'],
        'discountRatio': json['discountRatio'] == null ? undefined : json['discountRatio'],
        'timeDeal': json['timeDeal'] == null ? undefined : json['timeDeal'],
    };
}

export function CartItemResponseToJSON(json: any): CartItemResponse {
    return CartItemResponseToJSONTyped(json, false);
}

export function CartItemResponseToJSONTyped(value?: CartItemResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'cartItemId': value['cartItemId'],
        'itemId': value['itemId'],
        'itemName': value['itemName'],
        'itemImageUrl': value['itemImageUrl'],
        'quantity': value['quantity'],
        'unitPrice': value['unitPrice'],
        'totalPrice': value['totalPrice'],
        'discountRatio': value['discountRatio'],
        'timeDeal': value['timeDeal'],
    };
}

