/* tslint:disable */
/* eslint-disable */
/**
 * zzirit API
 * 찌릿 API 명세서
 *
 * The version of the OpenAPI document: v0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface EmailAuthDTO
 */
export interface EmailAuthDTO {
    /**
     * 
     * @type {string}
     * @memberof EmailAuthDTO
     */
    email: string;
}

/**
 * Check if a given object implements the EmailAuthDTO interface.
 */
export function instanceOfEmailAuthDTO(value: object): value is EmailAuthDTO {
    if (!('email' in value) || value['email'] === undefined) return false;
    return true;
}

export function EmailAuthDTOFromJSON(json: any): EmailAuthDTO {
    return EmailAuthDTOFromJSONTyped(json, false);
}

export function EmailAuthDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): EmailAuthDTO {
    if (json == null) {
        return json;
    }
    return {
        
        'email': json['email'],
    };
}

export function EmailAuthDTOToJSON(json: any): EmailAuthDTO {
    return EmailAuthDTOToJSONTyped(json, false);
}

export function EmailAuthDTOToJSONTyped(value?: EmailAuthDTO | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'email': value['email'],
    };
}

