/* tslint:disable */
/* eslint-disable */
/**
 * zzirit API
 * 찌릿 API 명세서
 *
 * The version of the OpenAPI document: v0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface EmailAuthVerificationDTO
 */
export interface EmailAuthVerificationDTO {
    /**
     * 
     * @type {string}
     * @memberof EmailAuthVerificationDTO
     */
    email: string;
    /**
     * 
     * @type {string}
     * @memberof EmailAuthVerificationDTO
     */
    code: string;
}

/**
 * Check if a given object implements the EmailAuthVerificationDTO interface.
 */
export function instanceOfEmailAuthVerificationDTO(value: object): value is EmailAuthVerificationDTO {
    if (!('email' in value) || value['email'] === undefined) return false;
    if (!('code' in value) || value['code'] === undefined) return false;
    return true;
}

export function EmailAuthVerificationDTOFromJSON(json: any): EmailAuthVerificationDTO {
    return EmailAuthVerificationDTOFromJSONTyped(json, false);
}

export function EmailAuthVerificationDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): EmailAuthVerificationDTO {
    if (json == null) {
        return json;
    }
    return {
        
        'email': json['email'],
        'code': json['code'],
    };
}

export function EmailAuthVerificationDTOToJSON(json: any): EmailAuthVerificationDTO {
    return EmailAuthVerificationDTOToJSONTyped(json, false);
}

export function EmailAuthVerificationDTOToJSONTyped(value?: EmailAuthVerificationDTO | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'email': value['email'],
        'code': value['code'],
    };
}

