/* tslint:disable */
/* eslint-disable */
/**
 * zzirit API
 * 찌릿 API 명세서
 *
 * The version of the OpenAPI document: v0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface EmailAuthVerifyRequest
 */
export interface EmailAuthVerifyRequest {
    /**
     * 
     * @type {string}
     * @memberof EmailAuthVerifyRequest
     */
    email: string;
    /**
     * 
     * @type {string}
     * @memberof EmailAuthVerifyRequest
     */
    code: string;
}

/**
 * Check if a given object implements the EmailAuthVerifyRequest interface.
 */
export function instanceOfEmailAuthVerifyRequest(value: object): value is EmailAuthVerifyRequest {
    if (!('email' in value) || value['email'] === undefined) return false;
    if (!('code' in value) || value['code'] === undefined) return false;
    return true;
}

export function EmailAuthVerifyRequestFromJSON(json: any): EmailAuthVerifyRequest {
    return EmailAuthVerifyRequestFromJSONTyped(json, false);
}

export function EmailAuthVerifyRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): EmailAuthVerifyRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'email': json['email'],
        'code': json['code'],
    };
}

export function EmailAuthVerifyRequestToJSON(json: any): EmailAuthVerifyRequest {
    return EmailAuthVerifyRequestToJSONTyped(json, false);
}

export function EmailAuthVerifyRequestToJSONTyped(value?: EmailAuthVerifyRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'email': value['email'],
        'code': value['code'],
    };
}

