/* tslint:disable */
/* eslint-disable */
/**
 * zzirit API
 * 찌릿 API 명세서
 *
 * The version of the OpenAPI document: v0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface EmailAuthRequest
 */
export interface EmailAuthRequest {
    /**
     * 
     * @type {string}
     * @memberof EmailAuthRequest
     */
    email: string;
}

/**
 * Check if a given object implements the EmailAuthRequest interface.
 */
export function instanceOfEmailAuthRequest(value: object): value is EmailAuthRequest {
    if (!('email' in value) || value['email'] === undefined) return false;
    return true;
}

export function EmailAuthRequestFromJSON(json: any): EmailAuthRequest {
    return EmailAuthRequestFromJSONTyped(json, false);
}

export function EmailAuthRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): EmailAuthRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'email': json['email'],
    };
}

export function EmailAuthRequestToJSON(json: any): EmailAuthRequest {
    return EmailAuthRequestToJSONTyped(json, false);
}

export function EmailAuthRequestToJSONTyped(value?: EmailAuthRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'email': value['email'],
    };
}

