/* tslint:disable */
/* eslint-disable */
/**
 * zzirit API
 * 찌릿 API 명세서
 *
 * The version of the OpenAPI document: v0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ImageUploadResponse
 */
export interface ImageUploadResponse {
    /**
     * 
     * @type {string}
     * @memberof ImageUploadResponse
     */
    imageUrl?: string;
}

/**
 * Check if a given object implements the ImageUploadResponse interface.
 */
export function instanceOfImageUploadResponse(value: object): value is ImageUploadResponse {
    return true;
}

export function ImageUploadResponseFromJSON(json: any): ImageUploadResponse {
    return ImageUploadResponseFromJSONTyped(json, false);
}

export function ImageUploadResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ImageUploadResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'imageUrl': json['imageUrl'] == null ? undefined : json['imageUrl'],
    };
}

export function ImageUploadResponseToJSON(json: any): ImageUploadResponse {
    return ImageUploadResponseToJSONTyped(json, false);
}

export function ImageUploadResponseToJSONTyped(value?: ImageUploadResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'imageUrl': value['imageUrl'],
    };
}

