/* tslint:disable */
/* eslint-disable */
/**
 * zzirit API
 * 찌릿 API 명세서
 *
 * The version of the OpenAPI document: v0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ItemFetchResponse
 */
export interface ItemFetchResponse {
    /**
     * 
     * @type {number}
     * @memberof ItemFetchResponse
     */
    itemId?: number;
    /**
     * 
     * @type {string}
     * @memberof ItemFetchResponse
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof ItemFetchResponse
     */
    type?: string;
    /**
     * 
     * @type {string}
     * @memberof ItemFetchResponse
     */
    brand?: string;
    /**
     * 
     * @type {number}
     * @memberof ItemFetchResponse
     */
    quantity?: number;
    /**
     * 
     * @type {string}
     * @memberof ItemFetchResponse
     */
    imageUrl?: string;
    /**
     * 
     * @type {number}
     * @memberof ItemFetchResponse
     */
    originalPrice?: number;
    /**
     * 
     * @type {number}
     * @memberof ItemFetchResponse
     */
    discountedPrice?: number;
    /**
     * 
     * @type {string}
     * @memberof ItemFetchResponse
     */
    itemStatus?: ItemFetchResponseItemStatusEnum;
    /**
     * 
     * @type {number}
     * @memberof ItemFetchResponse
     */
    discountRatio?: number;
    /**
     * 
     * @type {Date}
     * @memberof ItemFetchResponse
     */
    endTimeDeal?: Date;
}


/**
 * @export
 */
export const ItemFetchResponseItemStatusEnum = {
    None: 'NONE',
    TimeDeal: 'TIME_DEAL'
} as const;
export type ItemFetchResponseItemStatusEnum = typeof ItemFetchResponseItemStatusEnum[keyof typeof ItemFetchResponseItemStatusEnum];


/**
 * Check if a given object implements the ItemFetchResponse interface.
 */
export function instanceOfItemFetchResponse(value: object): value is ItemFetchResponse {
    return true;
}

export function ItemFetchResponseFromJSON(json: any): ItemFetchResponse {
    return ItemFetchResponseFromJSONTyped(json, false);
}

export function ItemFetchResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ItemFetchResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'itemId': json['itemId'] == null ? undefined : json['itemId'],
        'name': json['name'] == null ? undefined : json['name'],
        'type': json['type'] == null ? undefined : json['type'],
        'brand': json['brand'] == null ? undefined : json['brand'],
        'quantity': json['quantity'] == null ? undefined : json['quantity'],
        'imageUrl': json['imageUrl'] == null ? undefined : json['imageUrl'],
        'originalPrice': json['originalPrice'] == null ? undefined : json['originalPrice'],
        'discountedPrice': json['discountedPrice'] == null ? undefined : json['discountedPrice'],
        'itemStatus': json['itemStatus'] == null ? undefined : json['itemStatus'],
        'discountRatio': json['discountRatio'] == null ? undefined : json['discountRatio'],
        'endTimeDeal': json['endTimeDeal'] == null ? undefined : (new Date(json['endTimeDeal'])),
    };
}

export function ItemFetchResponseToJSON(json: any): ItemFetchResponse {
    return ItemFetchResponseToJSONTyped(json, false);
}

export function ItemFetchResponseToJSONTyped(value?: ItemFetchResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'itemId': value['itemId'],
        'name': value['name'],
        'type': value['type'],
        'brand': value['brand'],
        'quantity': value['quantity'],
        'imageUrl': value['imageUrl'],
        'originalPrice': value['originalPrice'],
        'discountedPrice': value['discountedPrice'],
        'itemStatus': value['itemStatus'],
        'discountRatio': value['discountRatio'],
        'endTimeDeal': value['endTimeDeal'] == null ? undefined : ((value['endTimeDeal']).toISOString()),
    };
}

