/* tslint:disable */
/* eslint-disable */
/**
 * zzirit API
 * 찌릿 API 명세서
 *
 * The version of the OpenAPI document: v0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ItemCreateRequest
 */
export interface ItemCreateRequest {
    /**
     * 
     * @type {string}
     * @memberof ItemCreateRequest
     */
    name?: string;
    /**
     * 
     * @type {number}
     * @memberof ItemCreateRequest
     */
    stockQuantity?: number;
    /**
     * 
     * @type {number}
     * @memberof ItemCreateRequest
     */
    price?: number;
    /**
     * 
     * @type {number}
     * @memberof ItemCreateRequest
     */
    typeId?: number;
    /**
     * 
     * @type {number}
     * @memberof ItemCreateRequest
     */
    brandId?: number;
}

/**
 * Check if a given object implements the ItemCreateRequest interface.
 */
export function instanceOfItemCreateRequest(value: object): value is ItemCreateRequest {
    return true;
}

export function ItemCreateRequestFromJSON(json: any): ItemCreateRequest {
    return ItemCreateRequestFromJSONTyped(json, false);
}

export function ItemCreateRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): ItemCreateRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'] == null ? undefined : json['name'],
        'stockQuantity': json['stockQuantity'] == null ? undefined : json['stockQuantity'],
        'price': json['price'] == null ? undefined : json['price'],
        'typeId': json['typeId'] == null ? undefined : json['typeId'],
        'brandId': json['brandId'] == null ? undefined : json['brandId'],
    };
}

export function ItemCreateRequestToJSON(json: any): ItemCreateRequest {
    return ItemCreateRequestToJSONTyped(json, false);
}

export function ItemCreateRequestToJSONTyped(value?: ItemCreateRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'stockQuantity': value['stockQuantity'],
        'price': value['price'],
        'typeId': value['typeId'],
        'brandId': value['brandId'],
    };
}

