/* tslint:disable */
/* eslint-disable */
/**
 * zzirit API
 * 찌릿 API 명세서
 *
 * The version of the OpenAPI document: v0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface MyPageInfoResponse
 */
export interface MyPageInfoResponse {
    /**
     * 
     * @type {string}
     * @memberof MyPageInfoResponse
     */
    memberName?: string;
    /**
     * 
     * @type {string}
     * @memberof MyPageInfoResponse
     */
    memberAddress?: string;
    /**
     * 
     * @type {string}
     * @memberof MyPageInfoResponse
     */
    memberAddressDetail?: string;
}

/**
 * Check if a given object implements the MyPageInfoResponse interface.
 */
export function instanceOfMyPageInfoResponse(value: object): value is MyPageInfoResponse {
    return true;
}

export function MyPageInfoResponseFromJSON(json: any): MyPageInfoResponse {
    return MyPageInfoResponseFromJSONTyped(json, false);
}

export function MyPageInfoResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): MyPageInfoResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'memberName': json['memberName'] == null ? undefined : json['memberName'],
        'memberAddress': json['memberAddress'] == null ? undefined : json['memberAddress'],
        'memberAddressDetail': json['memberAddressDetail'] == null ? undefined : json['memberAddressDetail'],
    };
}

export function MyPageInfoResponseToJSON(json: any): MyPageInfoResponse {
    return MyPageInfoResponseToJSONTyped(json, false);
}

export function MyPageInfoResponseToJSONTyped(value?: MyPageInfoResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'memberName': value['memberName'],
        'memberAddress': value['memberAddress'],
        'memberAddressDetail': value['memberAddressDetail'],
    };
}

