/* tslint:disable */
/* eslint-disable */
/**
 * zzirit API
 * 찌릿 API 명세서
 *
 * The version of the OpenAPI document: v0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { OrderItemCreateRequest } from './OrderItemCreateRequest';
import {
    OrderItemCreateRequestFromJSON,
    OrderItemCreateRequestFromJSONTyped,
    OrderItemCreateRequestToJSON,
    OrderItemCreateRequestToJSONTyped,
} from './OrderItemCreateRequest';

/**
 * 
 * @export
 * @interface OrderCreateRequest
 */
export interface OrderCreateRequest {
    /**
     * 
     * @type {string}
     * @memberof OrderCreateRequest
     */
    shippingRequest?: string;
    /**
     * 
     * @type {Array<OrderItemCreateRequest>}
     * @memberof OrderCreateRequest
     */
    items?: Array<OrderItemCreateRequest>;
}

/**
 * Check if a given object implements the OrderCreateRequest interface.
 */
export function instanceOfOrderCreateRequest(value: object): value is OrderCreateRequest {
    return true;
}

export function OrderCreateRequestFromJSON(json: any): OrderCreateRequest {
    return OrderCreateRequestFromJSONTyped(json, false);
}

export function OrderCreateRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): OrderCreateRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'shippingRequest': json['shippingRequest'] == null ? undefined : json['shippingRequest'],
        'items': json['items'] == null ? undefined : ((json['items'] as Array<any>).map(OrderItemCreateRequestFromJSON)),
    };
}

export function OrderCreateRequestToJSON(json: any): OrderCreateRequest {
    return OrderCreateRequestToJSONTyped(json, false);
}

export function OrderCreateRequestToJSONTyped(value?: OrderCreateRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'shippingRequest': value['shippingRequest'],
        'items': value['items'] == null ? undefined : ((value['items'] as Array<any>).map(OrderItemCreateRequestToJSON)),
    };
}

