/* tslint:disable */
/* eslint-disable */
/**
 * zzirit API
 * 찌릿 API 명세서
 *
 * The version of the OpenAPI document: v0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface OrderItemFetchResponse
 */
export interface OrderItemFetchResponse {
    /**
     * 
     * @type {string}
     * @memberof OrderItemFetchResponse
     */
    itemName?: string;
    /**
     * 
     * @type {number}
     * @memberof OrderItemFetchResponse
     */
    quantity?: number;
    /**
     * 
     * @type {string}
     * @memberof OrderItemFetchResponse
     */
    imageUrl?: string;
    /**
     * 
     * @type {number}
     * @memberof OrderItemFetchResponse
     */
    totalPrice?: number;
}

/**
 * Check if a given object implements the OrderItemFetchResponse interface.
 */
export function instanceOfOrderItemFetchResponse(value: object): value is OrderItemFetchResponse {
    return true;
}

export function OrderItemFetchResponseFromJSON(json: any): OrderItemFetchResponse {
    return OrderItemFetchResponseFromJSONTyped(json, false);
}

export function OrderItemFetchResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): OrderItemFetchResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'itemName': json['itemName'] == null ? undefined : json['itemName'],
        'quantity': json['quantity'] == null ? undefined : json['quantity'],
        'imageUrl': json['imageUrl'] == null ? undefined : json['imageUrl'],
        'totalPrice': json['totalPrice'] == null ? undefined : json['totalPrice'],
    };
}

export function OrderItemFetchResponseToJSON(json: any): OrderItemFetchResponse {
    return OrderItemFetchResponseToJSONTyped(json, false);
}

export function OrderItemFetchResponseToJSONTyped(value?: OrderItemFetchResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'itemName': value['itemName'],
        'quantity': value['quantity'],
        'imageUrl': value['imageUrl'],
        'totalPrice': value['totalPrice'],
    };
}

