/* tslint:disable */
/* eslint-disable */
/**
 * zzirit API
 * 찌릿 API 명세서
 *
 * The version of the OpenAPI document: v0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface OrderItemCreateRequest
 */
export interface OrderItemCreateRequest {
    /**
     * 
     * @type {number}
     * @memberof OrderItemCreateRequest
     */
    itemId?: number;
    /**
     * 
     * @type {number}
     * @memberof OrderItemCreateRequest
     */
    quantity?: number;
}

/**
 * Check if a given object implements the OrderItemCreateRequest interface.
 */
export function instanceOfOrderItemCreateRequest(value: object): value is OrderItemCreateRequest {
    return true;
}

export function OrderItemCreateRequestFromJSON(json: any): OrderItemCreateRequest {
    return OrderItemCreateRequestFromJSONTyped(json, false);
}

export function OrderItemCreateRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): OrderItemCreateRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'itemId': json['itemId'] == null ? undefined : json['itemId'],
        'quantity': json['quantity'] == null ? undefined : json['quantity'],
    };
}

export function OrderItemCreateRequestToJSON(json: any): OrderItemCreateRequest {
    return OrderItemCreateRequestToJSONTyped(json, false);
}

export function OrderItemCreateRequestToJSONTyped(value?: OrderItemCreateRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'itemId': value['itemId'],
        'quantity': value['quantity'],
    };
}

