/* tslint:disable */
/* eslint-disable */
/**
 * zzirit API
 * 찌릿 API 명세서
 *
 * The version of the OpenAPI document: v0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 주문 항목 요청 DTO
 * @export
 * @interface OrderItemCreateRequest
 */
export interface OrderItemCreateRequest {
    /**
     * 상품 ID
     * @type {number}
     * @memberof OrderItemCreateRequest
     */
    itemId: number;
    /**
     * 상품 이름
     * @type {string}
     * @memberof OrderItemCreateRequest
     */
    itemName: string;
    /**
     * 주문 수량
     * @type {number}
     * @memberof OrderItemCreateRequest
     */
    quantity?: number;
}

/**
 * Check if a given object implements the OrderItemCreateRequest interface.
 */
export function instanceOfOrderItemCreateRequest(value: object): value is OrderItemCreateRequest {
    if (!('itemId' in value) || value['itemId'] === undefined) return false;
    if (!('itemName' in value) || value['itemName'] === undefined) return false;
    return true;
}

export function OrderItemCreateRequestFromJSON(json: any): OrderItemCreateRequest {
    return OrderItemCreateRequestFromJSONTyped(json, false);
}

export function OrderItemCreateRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): OrderItemCreateRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'itemId': json['itemId'],
        'itemName': json['itemName'],
        'quantity': json['quantity'] == null ? undefined : json['quantity'],
    };
}

export function OrderItemCreateRequestToJSON(json: any): OrderItemCreateRequest {
    return OrderItemCreateRequestToJSONTyped(json, false);
}

export function OrderItemCreateRequestToJSONTyped(value?: OrderItemCreateRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'itemId': value['itemId'],
        'itemName': value['itemName'],
        'quantity': value['quantity'],
    };
}

