/* tslint:disable */
/* eslint-disable */
/**
 * zzirit API
 * 찌릿 API 명세서
 *
 * The version of the OpenAPI document: v0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { SimpleItemFetchResponse } from './SimpleItemFetchResponse';
import {
    SimpleItemFetchResponseFromJSON,
    SimpleItemFetchResponseFromJSONTyped,
    SimpleItemFetchResponseToJSON,
    SimpleItemFetchResponseToJSONTyped,
} from './SimpleItemFetchResponse';

/**
 * 
 * @export
 * @interface PageResponseSimpleItemFetchResponse
 */
export interface PageResponseSimpleItemFetchResponse {
    /**
     * 
     * @type {Array<SimpleItemFetchResponse>}
     * @memberof PageResponseSimpleItemFetchResponse
     */
    content?: Array<SimpleItemFetchResponse>;
    /**
     * 
     * @type {number}
     * @memberof PageResponseSimpleItemFetchResponse
     */
    pageNumber?: number;
    /**
     * 
     * @type {number}
     * @memberof PageResponseSimpleItemFetchResponse
     */
    pageSize?: number;
    /**
     * 
     * @type {number}
     * @memberof PageResponseSimpleItemFetchResponse
     */
    totalElements?: number;
    /**
     * 
     * @type {number}
     * @memberof PageResponseSimpleItemFetchResponse
     */
    totalPages?: number;
    /**
     * 
     * @type {boolean}
     * @memberof PageResponseSimpleItemFetchResponse
     */
    last?: boolean;
}

/**
 * Check if a given object implements the PageResponseSimpleItemFetchResponse interface.
 */
export function instanceOfPageResponseSimpleItemFetchResponse(value: object): value is PageResponseSimpleItemFetchResponse {
    return true;
}

export function PageResponseSimpleItemFetchResponseFromJSON(json: any): PageResponseSimpleItemFetchResponse {
    return PageResponseSimpleItemFetchResponseFromJSONTyped(json, false);
}

export function PageResponseSimpleItemFetchResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): PageResponseSimpleItemFetchResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'content': json['content'] == null ? undefined : ((json['content'] as Array<any>).map(SimpleItemFetchResponseFromJSON)),
        'pageNumber': json['pageNumber'] == null ? undefined : json['pageNumber'],
        'pageSize': json['pageSize'] == null ? undefined : json['pageSize'],
        'totalElements': json['totalElements'] == null ? undefined : json['totalElements'],
        'totalPages': json['totalPages'] == null ? undefined : json['totalPages'],
        'last': json['last'] == null ? undefined : json['last'],
    };
}

export function PageResponseSimpleItemFetchResponseToJSON(json: any): PageResponseSimpleItemFetchResponse {
    return PageResponseSimpleItemFetchResponseToJSONTyped(json, false);
}

export function PageResponseSimpleItemFetchResponseToJSONTyped(value?: PageResponseSimpleItemFetchResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'content': value['content'] == null ? undefined : ((value['content'] as Array<any>).map(SimpleItemFetchResponseToJSON)),
        'pageNumber': value['pageNumber'],
        'pageSize': value['pageSize'],
        'totalElements': value['totalElements'],
        'totalPages': value['totalPages'],
        'last': value['last'],
    };
}

