/* tslint:disable */
/* eslint-disable */
/**
 * zzirit API
 * 찌릿 API 명세서
 *
 * The version of the OpenAPI document: v0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { TimeDealFetchResponse } from './TimeDealFetchResponse';
import {
    TimeDealFetchResponseFromJSON,
    TimeDealFetchResponseFromJSONTyped,
    TimeDealFetchResponseToJSON,
    TimeDealFetchResponseToJSONTyped,
} from './TimeDealFetchResponse';

/**
 * 
 * @export
 * @interface PageResponseTimeDealFetchResponse
 */
export interface PageResponseTimeDealFetchResponse {
    /**
     * 
     * @type {Array<TimeDealFetchResponse>}
     * @memberof PageResponseTimeDealFetchResponse
     */
    content?: Array<TimeDealFetchResponse>;
    /**
     * 
     * @type {number}
     * @memberof PageResponseTimeDealFetchResponse
     */
    pageNumber?: number;
    /**
     * 
     * @type {number}
     * @memberof PageResponseTimeDealFetchResponse
     */
    pageSize?: number;
    /**
     * 
     * @type {number}
     * @memberof PageResponseTimeDealFetchResponse
     */
    totalElements?: number;
    /**
     * 
     * @type {number}
     * @memberof PageResponseTimeDealFetchResponse
     */
    totalPages?: number;
    /**
     * 
     * @type {boolean}
     * @memberof PageResponseTimeDealFetchResponse
     */
    last?: boolean;
}

/**
 * Check if a given object implements the PageResponseTimeDealFetchResponse interface.
 */
export function instanceOfPageResponseTimeDealFetchResponse(value: object): value is PageResponseTimeDealFetchResponse {
    return true;
}

export function PageResponseTimeDealFetchResponseFromJSON(json: any): PageResponseTimeDealFetchResponse {
    return PageResponseTimeDealFetchResponseFromJSONTyped(json, false);
}

export function PageResponseTimeDealFetchResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): PageResponseTimeDealFetchResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'content': json['content'] == null ? undefined : ((json['content'] as Array<any>).map(TimeDealFetchResponseFromJSON)),
        'pageNumber': json['pageNumber'] == null ? undefined : json['pageNumber'],
        'pageSize': json['pageSize'] == null ? undefined : json['pageSize'],
        'totalElements': json['totalElements'] == null ? undefined : json['totalElements'],
        'totalPages': json['totalPages'] == null ? undefined : json['totalPages'],
        'last': json['last'] == null ? undefined : json['last'],
    };
}

export function PageResponseTimeDealFetchResponseToJSON(json: any): PageResponseTimeDealFetchResponse {
    return PageResponseTimeDealFetchResponseToJSONTyped(json, false);
}

export function PageResponseTimeDealFetchResponseToJSONTyped(value?: PageResponseTimeDealFetchResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'content': value['content'] == null ? undefined : ((value['content'] as Array<any>).map(TimeDealFetchResponseToJSON)),
        'pageNumber': value['pageNumber'],
        'pageSize': value['pageSize'],
        'totalElements': value['totalElements'],
        'totalPages': value['totalPages'],
        'last': value['last'],
    };
}

