/* tslint:disable */
/* eslint-disable */
/**
 * zzirit API
 * 찌릿 API 명세서
 *
 * The version of the OpenAPI document: v0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { OrderFetchResponse } from './OrderFetchResponse';
import {
    OrderFetchResponseFromJSON,
    OrderFetchResponseFromJSONTyped,
    OrderFetchResponseToJSON,
    OrderFetchResponseToJSONTyped,
} from './OrderFetchResponse';

/**
 * 
 * @export
 * @interface PageResponseOrderFetchResponse
 */
export interface PageResponseOrderFetchResponse {
    /**
     * 
     * @type {Array<OrderFetchResponse>}
     * @memberof PageResponseOrderFetchResponse
     */
    content?: Array<OrderFetchResponse>;
    /**
     * 
     * @type {number}
     * @memberof PageResponseOrderFetchResponse
     */
    pageNumber?: number;
    /**
     * 
     * @type {number}
     * @memberof PageResponseOrderFetchResponse
     */
    pageSize?: number;
    /**
     * 
     * @type {number}
     * @memberof PageResponseOrderFetchResponse
     */
    totalElements?: number;
    /**
     * 
     * @type {number}
     * @memberof PageResponseOrderFetchResponse
     */
    totalPages?: number;
    /**
     * 
     * @type {boolean}
     * @memberof PageResponseOrderFetchResponse
     */
    last?: boolean;
}

/**
 * Check if a given object implements the PageResponseOrderFetchResponse interface.
 */
export function instanceOfPageResponseOrderFetchResponse(value: object): value is PageResponseOrderFetchResponse {
    return true;
}

export function PageResponseOrderFetchResponseFromJSON(json: any): PageResponseOrderFetchResponse {
    return PageResponseOrderFetchResponseFromJSONTyped(json, false);
}

export function PageResponseOrderFetchResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): PageResponseOrderFetchResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'content': json['content'] == null ? undefined : ((json['content'] as Array<any>).map(OrderFetchResponseFromJSON)),
        'pageNumber': json['pageNumber'] == null ? undefined : json['pageNumber'],
        'pageSize': json['pageSize'] == null ? undefined : json['pageSize'],
        'totalElements': json['totalElements'] == null ? undefined : json['totalElements'],
        'totalPages': json['totalPages'] == null ? undefined : json['totalPages'],
        'last': json['last'] == null ? undefined : json['last'],
    };
}

export function PageResponseOrderFetchResponseToJSON(json: any): PageResponseOrderFetchResponse {
    return PageResponseOrderFetchResponseToJSONTyped(json, false);
}

export function PageResponseOrderFetchResponseToJSONTyped(value?: PageResponseOrderFetchResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'content': value['content'] == null ? undefined : ((value['content'] as Array<any>).map(OrderFetchResponseToJSON)),
        'pageNumber': value['pageNumber'],
        'pageSize': value['pageSize'],
        'totalElements': value['totalElements'],
        'totalPages': value['totalPages'],
        'last': value['last'],
    };
}

