/* tslint:disable */
/* eslint-disable */
/**
 * zzirit API
 * 찌릿 API 명세서
 *
 * The version of the OpenAPI document: v0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { CurrentTimeDealFetchResponse } from './CurrentTimeDealFetchResponse';
import {
    CurrentTimeDealFetchResponseFromJSON,
    CurrentTimeDealFetchResponseFromJSONTyped,
    CurrentTimeDealFetchResponseToJSON,
    CurrentTimeDealFetchResponseToJSONTyped,
} from './CurrentTimeDealFetchResponse';

/**
 * 
 * @export
 * @interface PageResponseCurrentTimeDealFetchResponse
 */
export interface PageResponseCurrentTimeDealFetchResponse {
    /**
     * 
     * @type {Array<CurrentTimeDealFetchResponse>}
     * @memberof PageResponseCurrentTimeDealFetchResponse
     */
    content?: Array<CurrentTimeDealFetchResponse>;
    /**
     * 
     * @type {number}
     * @memberof PageResponseCurrentTimeDealFetchResponse
     */
    pageNumber?: number;
    /**
     * 
     * @type {number}
     * @memberof PageResponseCurrentTimeDealFetchResponse
     */
    pageSize?: number;
    /**
     * 
     * @type {number}
     * @memberof PageResponseCurrentTimeDealFetchResponse
     */
    totalElements?: number;
    /**
     * 
     * @type {number}
     * @memberof PageResponseCurrentTimeDealFetchResponse
     */
    totalPages?: number;
    /**
     * 
     * @type {boolean}
     * @memberof PageResponseCurrentTimeDealFetchResponse
     */
    last?: boolean;
}

/**
 * Check if a given object implements the PageResponseCurrentTimeDealFetchResponse interface.
 */
export function instanceOfPageResponseCurrentTimeDealFetchResponse(value: object): value is PageResponseCurrentTimeDealFetchResponse {
    return true;
}

export function PageResponseCurrentTimeDealFetchResponseFromJSON(json: any): PageResponseCurrentTimeDealFetchResponse {
    return PageResponseCurrentTimeDealFetchResponseFromJSONTyped(json, false);
}

export function PageResponseCurrentTimeDealFetchResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): PageResponseCurrentTimeDealFetchResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'content': json['content'] == null ? undefined : ((json['content'] as Array<any>).map(CurrentTimeDealFetchResponseFromJSON)),
        'pageNumber': json['pageNumber'] == null ? undefined : json['pageNumber'],
        'pageSize': json['pageSize'] == null ? undefined : json['pageSize'],
        'totalElements': json['totalElements'] == null ? undefined : json['totalElements'],
        'totalPages': json['totalPages'] == null ? undefined : json['totalPages'],
        'last': json['last'] == null ? undefined : json['last'],
    };
}

export function PageResponseCurrentTimeDealFetchResponseToJSON(json: any): PageResponseCurrentTimeDealFetchResponse {
    return PageResponseCurrentTimeDealFetchResponseToJSONTyped(json, false);
}

export function PageResponseCurrentTimeDealFetchResponseToJSONTyped(value?: PageResponseCurrentTimeDealFetchResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'content': value['content'] == null ? undefined : ((value['content'] as Array<any>).map(CurrentTimeDealFetchResponseToJSON)),
        'pageNumber': value['pageNumber'],
        'pageSize': value['pageSize'],
        'totalElements': value['totalElements'],
        'totalPages': value['totalPages'],
        'last': value['last'],
    };
}

