/* tslint:disable */
/* eslint-disable */
/**
 * zzirit API
 * 찌릿 API 명세서
 *
 * The version of the OpenAPI document: v0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { AdminItemFetchResponse } from './AdminItemFetchResponse';
import {
    AdminItemFetchResponseFromJSON,
    AdminItemFetchResponseFromJSONTyped,
    AdminItemFetchResponseToJSON,
    AdminItemFetchResponseToJSONTyped,
} from './AdminItemFetchResponse';

/**
 * 
 * @export
 * @interface PageResponseAdminItemFetchResponse
 */
export interface PageResponseAdminItemFetchResponse {
    /**
     * 
     * @type {Array<AdminItemFetchResponse>}
     * @memberof PageResponseAdminItemFetchResponse
     */
    content?: Array<AdminItemFetchResponse>;
    /**
     * 
     * @type {number}
     * @memberof PageResponseAdminItemFetchResponse
     */
    pageNumber?: number;
    /**
     * 
     * @type {number}
     * @memberof PageResponseAdminItemFetchResponse
     */
    pageSize?: number;
    /**
     * 
     * @type {number}
     * @memberof PageResponseAdminItemFetchResponse
     */
    totalElements?: number;
    /**
     * 
     * @type {number}
     * @memberof PageResponseAdminItemFetchResponse
     */
    totalPages?: number;
    /**
     * 
     * @type {boolean}
     * @memberof PageResponseAdminItemFetchResponse
     */
    last?: boolean;
}

/**
 * Check if a given object implements the PageResponseAdminItemFetchResponse interface.
 */
export function instanceOfPageResponseAdminItemFetchResponse(value: object): value is PageResponseAdminItemFetchResponse {
    return true;
}

export function PageResponseAdminItemFetchResponseFromJSON(json: any): PageResponseAdminItemFetchResponse {
    return PageResponseAdminItemFetchResponseFromJSONTyped(json, false);
}

export function PageResponseAdminItemFetchResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): PageResponseAdminItemFetchResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'content': json['content'] == null ? undefined : ((json['content'] as Array<any>).map(AdminItemFetchResponseFromJSON)),
        'pageNumber': json['pageNumber'] == null ? undefined : json['pageNumber'],
        'pageSize': json['pageSize'] == null ? undefined : json['pageSize'],
        'totalElements': json['totalElements'] == null ? undefined : json['totalElements'],
        'totalPages': json['totalPages'] == null ? undefined : json['totalPages'],
        'last': json['last'] == null ? undefined : json['last'],
    };
}

export function PageResponseAdminItemFetchResponseToJSON(json: any): PageResponseAdminItemFetchResponse {
    return PageResponseAdminItemFetchResponseToJSONTyped(json, false);
}

export function PageResponseAdminItemFetchResponseToJSONTyped(value?: PageResponseAdminItemFetchResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'content': value['content'] == null ? undefined : ((value['content'] as Array<any>).map(AdminItemFetchResponseToJSON)),
        'pageNumber': value['pageNumber'],
        'pageSize': value['pageSize'],
        'totalElements': value['totalElements'],
        'totalPages': value['totalPages'],
        'last': value['last'],
    };
}

