/* tslint:disable */
/* eslint-disable */
/**
 * zzirit API
 * 찌릿 API 명세서
 *
 * The version of the OpenAPI document: v0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ItemFetchQueryResponse } from './ItemFetchQueryResponse';
import {
    ItemFetchQueryResponseFromJSON,
    ItemFetchQueryResponseFromJSONTyped,
    ItemFetchQueryResponseToJSON,
    ItemFetchQueryResponseToJSONTyped,
} from './ItemFetchQueryResponse';

/**
 * 
 * @export
 * @interface PageResponseItemFetchQueryResponse
 */
export interface PageResponseItemFetchQueryResponse {
    /**
     * 
     * @type {Array<ItemFetchQueryResponse>}
     * @memberof PageResponseItemFetchQueryResponse
     */
    content?: Array<ItemFetchQueryResponse>;
    /**
     * 
     * @type {number}
     * @memberof PageResponseItemFetchQueryResponse
     */
    pageNumber?: number;
    /**
     * 
     * @type {number}
     * @memberof PageResponseItemFetchQueryResponse
     */
    pageSize?: number;
    /**
     * 
     * @type {number}
     * @memberof PageResponseItemFetchQueryResponse
     */
    totalElements?: number;
    /**
     * 
     * @type {number}
     * @memberof PageResponseItemFetchQueryResponse
     */
    totalPages?: number;
    /**
     * 
     * @type {boolean}
     * @memberof PageResponseItemFetchQueryResponse
     */
    last?: boolean;
}

/**
 * Check if a given object implements the PageResponseItemFetchQueryResponse interface.
 */
export function instanceOfPageResponseItemFetchQueryResponse(value: object): value is PageResponseItemFetchQueryResponse {
    return true;
}

export function PageResponseItemFetchQueryResponseFromJSON(json: any): PageResponseItemFetchQueryResponse {
    return PageResponseItemFetchQueryResponseFromJSONTyped(json, false);
}

export function PageResponseItemFetchQueryResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): PageResponseItemFetchQueryResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'content': json['content'] == null ? undefined : ((json['content'] as Array<any>).map(ItemFetchQueryResponseFromJSON)),
        'pageNumber': json['pageNumber'] == null ? undefined : json['pageNumber'],
        'pageSize': json['pageSize'] == null ? undefined : json['pageSize'],
        'totalElements': json['totalElements'] == null ? undefined : json['totalElements'],
        'totalPages': json['totalPages'] == null ? undefined : json['totalPages'],
        'last': json['last'] == null ? undefined : json['last'],
    };
}

export function PageResponseItemFetchQueryResponseToJSON(json: any): PageResponseItemFetchQueryResponse {
    return PageResponseItemFetchQueryResponseToJSONTyped(json, false);
}

export function PageResponseItemFetchQueryResponseToJSONTyped(value?: PageResponseItemFetchQueryResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'content': value['content'] == null ? undefined : ((value['content'] as Array<any>).map(ItemFetchQueryResponseToJSON)),
        'pageNumber': value['pageNumber'],
        'pageSize': value['pageSize'],
        'totalElements': value['totalElements'],
        'totalPages': value['totalPages'],
        'last': value['last'],
    };
}

