/* tslint:disable */
/* eslint-disable */
/**
 * zzirit API
 * 찌릿 API 명세서
 *
 * The version of the OpenAPI document: v0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { OrderItemRequestDto } from './OrderItemRequestDto';
import {
    OrderItemRequestDtoFromJSON,
    OrderItemRequestDtoFromJSONTyped,
    OrderItemRequestDtoToJSON,
    OrderItemRequestDtoToJSONTyped,
} from './OrderItemRequestDto';

/**
 * 
 * @export
 * @interface PaymentRequestDto
 */
export interface PaymentRequestDto {
    /**
     * 
     * @type {Array<OrderItemRequestDto>}
     * @memberof PaymentRequestDto
     */
    orderItems?: Array<OrderItemRequestDto>;
    /**
     * 
     * @type {number}
     * @memberof PaymentRequestDto
     */
    totalAmount?: number;
    /**
     * 
     * @type {string}
     * @memberof PaymentRequestDto
     */
    shippingAddress?: string;
    /**
     * 
     * @type {string}
     * @memberof PaymentRequestDto
     */
    shippingAddressDetail?: string;
}

/**
 * Check if a given object implements the PaymentRequestDto interface.
 */
export function instanceOfPaymentRequestDto(value: object): value is PaymentRequestDto {
    return true;
}

export function PaymentRequestDtoFromJSON(json: any): PaymentRequestDto {
    return PaymentRequestDtoFromJSONTyped(json, false);
}

export function PaymentRequestDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): PaymentRequestDto {
    if (json == null) {
        return json;
    }
    return {
        
        'orderItems': json['orderItems'] == null ? undefined : ((json['orderItems'] as Array<any>).map(OrderItemRequestDtoFromJSON)),
        'totalAmount': json['totalAmount'] == null ? undefined : json['totalAmount'],
        'shippingAddress': json['shippingAddress'] == null ? undefined : json['shippingAddress'],
        'shippingAddressDetail': json['shippingAddressDetail'] == null ? undefined : json['shippingAddressDetail'],
    };
}

export function PaymentRequestDtoToJSON(json: any): PaymentRequestDto {
    return PaymentRequestDtoToJSONTyped(json, false);
}

export function PaymentRequestDtoToJSONTyped(value?: PaymentRequestDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'orderItems': value['orderItems'] == null ? undefined : ((value['orderItems'] as Array<any>).map(OrderItemRequestDtoToJSON)),
        'totalAmount': value['totalAmount'],
        'shippingAddress': value['shippingAddress'],
        'shippingAddressDetail': value['shippingAddressDetail'],
    };
}

