/* tslint:disable */
/* eslint-disable */
/**
 * zzirit API
 * 찌릿 API 명세서
 *
 * The version of the OpenAPI document: v0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { OrderItemCreateRequest } from './OrderItemCreateRequest';
import {
    OrderItemCreateRequestFromJSON,
    OrderItemCreateRequestFromJSONTyped,
    OrderItemCreateRequestToJSON,
    OrderItemCreateRequestToJSONTyped,
} from './OrderItemCreateRequest';

/**
 * 
 * @export
 * @interface PaymentRequest
 */
export interface PaymentRequest {
    /**
     * 
     * @type {Array<OrderItemCreateRequest>}
     * @memberof PaymentRequest
     */
    orderItems?: Array<OrderItemCreateRequest>;
    /**
     * 
     * @type {number}
     * @memberof PaymentRequest
     */
    totalAmount?: number;
    /**
     * 
     * @type {string}
     * @memberof PaymentRequest
     */
    shippingRequest?: string;
    /**
     * 
     * @type {string}
     * @memberof PaymentRequest
     */
    address?: string;
    /**
     * 
     * @type {string}
     * @memberof PaymentRequest
     */
    addressDetail?: string;
}

/**
 * Check if a given object implements the PaymentRequest interface.
 */
export function instanceOfPaymentRequest(value: object): value is PaymentRequest {
    return true;
}

export function PaymentRequestFromJSON(json: any): PaymentRequest {
    return PaymentRequestFromJSONTyped(json, false);
}

export function PaymentRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): PaymentRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'orderItems': json['orderItems'] == null ? undefined : ((json['orderItems'] as Array<any>).map(OrderItemCreateRequestFromJSON)),
        'totalAmount': json['totalAmount'] == null ? undefined : json['totalAmount'],
        'shippingRequest': json['shippingRequest'] == null ? undefined : json['shippingRequest'],
        'address': json['address'] == null ? undefined : json['address'],
        'addressDetail': json['addressDetail'] == null ? undefined : json['addressDetail'],
    };
}

export function PaymentRequestToJSON(json: any): PaymentRequest {
    return PaymentRequestToJSONTyped(json, false);
}

export function PaymentRequestToJSONTyped(value?: PaymentRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'orderItems': value['orderItems'] == null ? undefined : ((value['orderItems'] as Array<any>).map(OrderItemCreateRequestToJSON)),
        'totalAmount': value['totalAmount'],
        'shippingRequest': value['shippingRequest'],
        'address': value['address'],
        'addressDetail': value['addressDetail'],
    };
}

