/* tslint:disable */
/* eslint-disable */
/**
 * zzirit API
 * 찌릿 API 명세서
 *
 * The version of the OpenAPI document: v0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 결제 확인 응답 DTO
 * @export
 * @interface PaymentConfirmResponse
 */
export interface PaymentConfirmResponse {
    /**
     * 주문번호
     * @type {string}
     * @memberof PaymentConfirmResponse
     */
    orderId?: string;
    /**
     * 결제 키
     * @type {string}
     * @memberof PaymentConfirmResponse
     */
    paymentKey?: string;
    /**
     * 결제 금액
     * @type {number}
     * @memberof PaymentConfirmResponse
     */
    amount?: number;
}

/**
 * Check if a given object implements the PaymentConfirmResponse interface.
 */
export function instanceOfPaymentConfirmResponse(value: object): value is PaymentConfirmResponse {
    return true;
}

export function PaymentConfirmResponseFromJSON(json: any): PaymentConfirmResponse {
    return PaymentConfirmResponseFromJSONTyped(json, false);
}

export function PaymentConfirmResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): PaymentConfirmResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'orderId': json['orderId'] == null ? undefined : json['orderId'],
        'paymentKey': json['paymentKey'] == null ? undefined : json['paymentKey'],
        'amount': json['amount'] == null ? undefined : json['amount'],
    };
}

export function PaymentConfirmResponseToJSON(json: any): PaymentConfirmResponse {
    return PaymentConfirmResponseToJSONTyped(json, false);
}

export function PaymentConfirmResponseToJSONTyped(value?: PaymentConfirmResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'orderId': value['orderId'],
        'paymentKey': value['paymentKey'],
        'amount': value['amount'],
    };
}

