/* tslint:disable */
/* eslint-disable */
/**
 * zzirit API
 * 찌릿 API 명세서
 *
 * The version of the OpenAPI document: v0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 결제 초기화 응답 DTO
 * @export
 * @interface PaymentInitResponse
 */
export interface PaymentInitResponse {
    /**
     * 주문 ID
     * @type {string}
     * @memberof PaymentInitResponse
     */
    orderId?: string;
    /**
     * 결제 금액 (단위: 원)
     * @type {number}
     * @memberof PaymentInitResponse
     */
    amount?: number;
    /**
     * 주문명
     * @type {string}
     * @memberof PaymentInitResponse
     */
    orderName?: string;
    /**
     * 구매자 이름
     * @type {string}
     * @memberof PaymentInitResponse
     */
    customerName?: string;
}

/**
 * Check if a given object implements the PaymentInitResponse interface.
 */
export function instanceOfPaymentInitResponse(value: object): value is PaymentInitResponse {
    return true;
}

export function PaymentInitResponseFromJSON(json: any): PaymentInitResponse {
    return PaymentInitResponseFromJSONTyped(json, false);
}

export function PaymentInitResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): PaymentInitResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'orderId': json['orderId'] == null ? undefined : json['orderId'],
        'amount': json['amount'] == null ? undefined : json['amount'],
        'orderName': json['orderName'] == null ? undefined : json['orderName'],
        'customerName': json['customerName'] == null ? undefined : json['customerName'],
    };
}

export function PaymentInitResponseToJSON(json: any): PaymentInitResponse {
    return PaymentInitResponseToJSONTyped(json, false);
}

export function PaymentInitResponseToJSONTyped(value?: PaymentInitResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'orderId': value['orderId'],
        'amount': value['amount'],
        'orderName': value['orderName'],
        'customerName': value['customerName'],
    };
}

