/* tslint:disable */
/* eslint-disable */
/**
 * zzirit API
 * 찌릿 API 명세서
 *
 * The version of the OpenAPI document: v0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SignupDTO
 */
export interface SignupDTO {
    /**
     * 
     * @type {string}
     * @memberof SignupDTO
     */
    memberName: string;
    /**
     * 
     * @type {string}
     * @memberof SignupDTO
     */
    memberEmail: string;
    /**
     * 
     * @type {string}
     * @memberof SignupDTO
     */
    memberPassword: string;
    /**
     * 
     * @type {string}
     * @memberof SignupDTO
     */
    memberAddress?: string;
    /**
     * 
     * @type {string}
     * @memberof SignupDTO
     */
    memberAddressDetail?: string;
}

/**
 * Check if a given object implements the SignupDTO interface.
 */
export function instanceOfSignupDTO(value: object): value is SignupDTO {
    if (!('memberName' in value) || value['memberName'] === undefined) return false;
    if (!('memberEmail' in value) || value['memberEmail'] === undefined) return false;
    if (!('memberPassword' in value) || value['memberPassword'] === undefined) return false;
    return true;
}

export function SignupDTOFromJSON(json: any): SignupDTO {
    return SignupDTOFromJSONTyped(json, false);
}

export function SignupDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): SignupDTO {
    if (json == null) {
        return json;
    }
    return {
        
        'memberName': json['memberName'],
        'memberEmail': json['memberEmail'],
        'memberPassword': json['memberPassword'],
        'memberAddress': json['memberAddress'] == null ? undefined : json['memberAddress'],
        'memberAddressDetail': json['memberAddressDetail'] == null ? undefined : json['memberAddressDetail'],
    };
}

export function SignupDTOToJSON(json: any): SignupDTO {
    return SignupDTOToJSONTyped(json, false);
}

export function SignupDTOToJSONTyped(value?: SignupDTO | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'memberName': value['memberName'],
        'memberEmail': value['memberEmail'],
        'memberPassword': value['memberPassword'],
        'memberAddress': value['memberAddress'],
        'memberAddressDetail': value['memberAddressDetail'],
    };
}

