/* tslint:disable */
/* eslint-disable */
/**
 * zzirit API
 * 찌릿 API 명세서
 *
 * The version of the OpenAPI document: v0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SignupRequest
 */
export interface SignupRequest {
    /**
     * 
     * @type {string}
     * @memberof SignupRequest
     */
    memberName: string;
    /**
     * 
     * @type {string}
     * @memberof SignupRequest
     */
    memberEmail: string;
    /**
     * 
     * @type {string}
     * @memberof SignupRequest
     */
    memberPassword: string;
    /**
     * 
     * @type {string}
     * @memberof SignupRequest
     */
    memberAddress?: string;
    /**
     * 
     * @type {string}
     * @memberof SignupRequest
     */
    memberAddressDetail?: string;
}

/**
 * Check if a given object implements the SignupRequest interface.
 */
export function instanceOfSignupRequest(value: object): value is SignupRequest {
    if (!('memberName' in value) || value['memberName'] === undefined) return false;
    if (!('memberEmail' in value) || value['memberEmail'] === undefined) return false;
    if (!('memberPassword' in value) || value['memberPassword'] === undefined) return false;
    return true;
}

export function SignupRequestFromJSON(json: any): SignupRequest {
    return SignupRequestFromJSONTyped(json, false);
}

export function SignupRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): SignupRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'memberName': json['memberName'],
        'memberEmail': json['memberEmail'],
        'memberPassword': json['memberPassword'],
        'memberAddress': json['memberAddress'] == null ? undefined : json['memberAddress'],
        'memberAddressDetail': json['memberAddressDetail'] == null ? undefined : json['memberAddressDetail'],
    };
}

export function SignupRequestToJSON(json: any): SignupRequest {
    return SignupRequestToJSONTyped(json, false);
}

export function SignupRequestToJSONTyped(value?: SignupRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'memberName': value['memberName'],
        'memberEmail': value['memberEmail'],
        'memberPassword': value['memberPassword'],
        'memberAddress': value['memberAddress'],
        'memberAddressDetail': value['memberAddressDetail'],
    };
}

