/* tslint:disable */
/* eslint-disable */
/**
 * zzirit API
 * 찌릿 API 명세서
 *
 * The version of the OpenAPI document: v0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SimpleItemResponse
 */
export interface SimpleItemResponse {
    /**
     * 
     * @type {number}
     * @memberof SimpleItemResponse
     */
    itemId?: number;
    /**
     * 
     * @type {string}
     * @memberof SimpleItemResponse
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof SimpleItemResponse
     */
    type?: string;
    /**
     * 
     * @type {string}
     * @memberof SimpleItemResponse
     */
    brand?: string;
    /**
     * 
     * @type {number}
     * @memberof SimpleItemResponse
     */
    price?: number;
    /**
     * 
     * @type {string}
     * @memberof SimpleItemResponse
     */
    timeDealStatus?: SimpleItemResponseTimeDealStatusEnum;
}


/**
 * @export
 */
export const SimpleItemResponseTimeDealStatusEnum = {
    None: 'NONE',
    TimeDeal: 'TIME_DEAL'
} as const;
export type SimpleItemResponseTimeDealStatusEnum = typeof SimpleItemResponseTimeDealStatusEnum[keyof typeof SimpleItemResponseTimeDealStatusEnum];


/**
 * Check if a given object implements the SimpleItemResponse interface.
 */
export function instanceOfSimpleItemResponse(value: object): value is SimpleItemResponse {
    return true;
}

export function SimpleItemResponseFromJSON(json: any): SimpleItemResponse {
    return SimpleItemResponseFromJSONTyped(json, false);
}

export function SimpleItemResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): SimpleItemResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'itemId': json['itemId'] == null ? undefined : json['itemId'],
        'name': json['name'] == null ? undefined : json['name'],
        'type': json['type'] == null ? undefined : json['type'],
        'brand': json['brand'] == null ? undefined : json['brand'],
        'price': json['price'] == null ? undefined : json['price'],
        'timeDealStatus': json['timeDealStatus'] == null ? undefined : json['timeDealStatus'],
    };
}

export function SimpleItemResponseToJSON(json: any): SimpleItemResponse {
    return SimpleItemResponseToJSONTyped(json, false);
}

export function SimpleItemResponseToJSONTyped(value?: SimpleItemResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'itemId': value['itemId'],
        'name': value['name'],
        'type': value['type'],
        'brand': value['brand'],
        'price': value['price'],
        'timeDealStatus': value['timeDealStatus'],
    };
}

