/* tslint:disable */
/* eslint-disable */
/**
 * zzirit API
 * 찌릿 API 명세서
 *
 * The version of the OpenAPI document: v0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SocialSignupDTO
 */
export interface SocialSignupDTO {
    /**
     * 
     * @type {string}
     * @memberof SocialSignupDTO
     */
    memberName: string;
    /**
     * 
     * @type {string}
     * @memberof SocialSignupDTO
     */
    memberAddress?: string;
    /**
     * 
     * @type {string}
     * @memberof SocialSignupDTO
     */
    memberAddressDetail?: string;
    /**
     * 
     * @type {string}
     * @memberof SocialSignupDTO
     */
    memberPassword: string;
}

/**
 * Check if a given object implements the SocialSignupDTO interface.
 */
export function instanceOfSocialSignupDTO(value: object): value is SocialSignupDTO {
    if (!('memberName' in value) || value['memberName'] === undefined) return false;
    if (!('memberPassword' in value) || value['memberPassword'] === undefined) return false;
    return true;
}

export function SocialSignupDTOFromJSON(json: any): SocialSignupDTO {
    return SocialSignupDTOFromJSONTyped(json, false);
}

export function SocialSignupDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): SocialSignupDTO {
    if (json == null) {
        return json;
    }
    return {
        
        'memberName': json['memberName'],
        'memberAddress': json['memberAddress'] == null ? undefined : json['memberAddress'],
        'memberAddressDetail': json['memberAddressDetail'] == null ? undefined : json['memberAddressDetail'],
        'memberPassword': json['memberPassword'],
    };
}

export function SocialSignupDTOToJSON(json: any): SocialSignupDTO {
    return SocialSignupDTOToJSONTyped(json, false);
}

export function SocialSignupDTOToJSONTyped(value?: SocialSignupDTO | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'memberName': value['memberName'],
        'memberAddress': value['memberAddress'],
        'memberAddressDetail': value['memberAddressDetail'],
        'memberPassword': value['memberPassword'],
    };
}

