/* tslint:disable */
/* eslint-disable */
/**
 * zzirit API
 * 찌릿 API 명세서
 *
 * The version of the OpenAPI document: v0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TimeDealFetchItem
 */
export interface TimeDealFetchItem {
    /**
     * 
     * @type {number}
     * @memberof TimeDealFetchItem
     */
    itemId?: number;
    /**
     * 
     * @type {string}
     * @memberof TimeDealFetchItem
     */
    itemName?: string;
    /**
     * 
     * @type {number}
     * @memberof TimeDealFetchItem
     */
    quantity?: number;
    /**
     * 
     * @type {number}
     * @memberof TimeDealFetchItem
     */
    originalPrice?: number;
    /**
     * 
     * @type {number}
     * @memberof TimeDealFetchItem
     */
    discountedPrice?: number;
}

/**
 * Check if a given object implements the TimeDealFetchItem interface.
 */
export function instanceOfTimeDealFetchItem(value: object): value is TimeDealFetchItem {
    return true;
}

export function TimeDealFetchItemFromJSON(json: any): TimeDealFetchItem {
    return TimeDealFetchItemFromJSONTyped(json, false);
}

export function TimeDealFetchItemFromJSONTyped(json: any, ignoreDiscriminator: boolean): TimeDealFetchItem {
    if (json == null) {
        return json;
    }
    return {
        
        'itemId': json['itemId'] == null ? undefined : json['itemId'],
        'itemName': json['itemName'] == null ? undefined : json['itemName'],
        'quantity': json['quantity'] == null ? undefined : json['quantity'],
        'originalPrice': json['originalPrice'] == null ? undefined : json['originalPrice'],
        'discountedPrice': json['discountedPrice'] == null ? undefined : json['discountedPrice'],
    };
}

export function TimeDealFetchItemToJSON(json: any): TimeDealFetchItem {
    return TimeDealFetchItemToJSONTyped(json, false);
}

export function TimeDealFetchItemToJSONTyped(value?: TimeDealFetchItem | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'itemId': value['itemId'],
        'itemName': value['itemName'],
        'quantity': value['quantity'],
        'originalPrice': value['originalPrice'],
        'discountedPrice': value['discountedPrice'],
    };
}

