/* tslint:disable */
/* eslint-disable */
/**
 * zzirit API
 * 찌릿 API 명세서
 *
 * The version of the OpenAPI document: v0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { TimeDealCreateItem } from './TimeDealCreateItem';
import {
    TimeDealCreateItemFromJSON,
    TimeDealCreateItemFromJSONTyped,
    TimeDealCreateItemToJSON,
    TimeDealCreateItemToJSONTyped,
} from './TimeDealCreateItem';

/**
 * 타임딜 등록 응답
 * @export
 * @interface TimeDealCreateResponse
 */
export interface TimeDealCreateResponse {
    /**
     * 타임딜 ID
     * @type {number}
     * @memberof TimeDealCreateResponse
     */
    timeDealId?: number;
    /**
     * 타임딜 제목
     * @type {string}
     * @memberof TimeDealCreateResponse
     */
    title?: string;
    /**
     * 시작 시간
     * @type {string}
     * @memberof TimeDealCreateResponse
     */
    startTime?: string;
    /**
     * 종료 시간
     * @type {string}
     * @memberof TimeDealCreateResponse
     */
    endTime?: string;
    /**
     * 할인율 (%)
     * @type {number}
     * @memberof TimeDealCreateResponse
     */
    discountRate?: number;
    /**
     * 타임딜 대상 상품 목록
     * @type {Array<TimeDealCreateItem>}
     * @memberof TimeDealCreateResponse
     */
    items?: Array<TimeDealCreateItem>;
}

/**
 * Check if a given object implements the TimeDealCreateResponse interface.
 */
export function instanceOfTimeDealCreateResponse(value: object): value is TimeDealCreateResponse {
    return true;
}

export function TimeDealCreateResponseFromJSON(json: any): TimeDealCreateResponse {
    return TimeDealCreateResponseFromJSONTyped(json, false);
}

export function TimeDealCreateResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): TimeDealCreateResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'timeDealId': json['timeDealId'] == null ? undefined : json['timeDealId'],
        'title': json['title'] == null ? undefined : json['title'],
        'startTime': json['startTime'] == null ? undefined : json['startTime'],
        'endTime': json['endTime'] == null ? undefined : json['endTime'],
        'discountRate': json['discountRate'] == null ? undefined : json['discountRate'],
        'items': json['items'] == null ? undefined : ((json['items'] as Array<any>).map(TimeDealCreateItemFromJSON)),
    };
}

export function TimeDealCreateResponseToJSON(json: any): TimeDealCreateResponse {
    return TimeDealCreateResponseToJSONTyped(json, false);
}

export function TimeDealCreateResponseToJSONTyped(value?: TimeDealCreateResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'timeDealId': value['timeDealId'],
        'title': value['title'],
        'startTime': value['startTime'],
        'endTime': value['endTime'],
        'discountRate': value['discountRate'],
        'items': value['items'] == null ? undefined : ((value['items'] as Array<any>).map(TimeDealCreateItemToJSON)),
    };
}

