/* tslint:disable */
/* eslint-disable */
/**
 * zzirit API
 * 찌릿 API 명세서
 *
 * The version of the OpenAPI document: v0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 타임딜 생성 모달에서 사용하는 상품 정보
 * @export
 * @interface TimeDealModalItem
 */
export interface TimeDealModalItem {
    /**
     * 상품 ID
     * @type {number}
     * @memberof TimeDealModalItem
     */
    itemId?: number;
    /**
     * 상품 이름
     * @type {string}
     * @memberof TimeDealModalItem
     */
    itemName?: string;
    /**
     * 기존 가격
     * @type {number}
     * @memberof TimeDealModalItem
     */
    originalPrice?: number;
}

/**
 * Check if a given object implements the TimeDealModalItem interface.
 */
export function instanceOfTimeDealModalItem(value: object): value is TimeDealModalItem {
    return true;
}

export function TimeDealModalItemFromJSON(json: any): TimeDealModalItem {
    return TimeDealModalItemFromJSONTyped(json, false);
}

export function TimeDealModalItemFromJSONTyped(json: any, ignoreDiscriminator: boolean): TimeDealModalItem {
    if (json == null) {
        return json;
    }
    return {
        
        'itemId': json['itemId'] == null ? undefined : json['itemId'],
        'itemName': json['itemName'] == null ? undefined : json['itemName'],
        'originalPrice': json['originalPrice'] == null ? undefined : json['originalPrice'],
    };
}

export function TimeDealModalItemToJSON(json: any): TimeDealModalItem {
    return TimeDealModalItemToJSONTyped(json, false);
}

export function TimeDealModalItemToJSONTyped(value?: TimeDealModalItem | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'itemId': value['itemId'],
        'itemName': value['itemName'],
        'originalPrice': value['originalPrice'],
    };
}

