/* tslint:disable */
/* eslint-disable */
/**
 * zzirit API
 * 찌릿 API 명세서
 *
 * The version of the OpenAPI document: v0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TypeResponse
 */
export interface TypeResponse {
    /**
     * 
     * @type {number}
     * @memberof TypeResponse
     */
    typeId?: number;
    /**
     * 
     * @type {string}
     * @memberof TypeResponse
     */
    name?: string;
}

/**
 * Check if a given object implements the TypeResponse interface.
 */
export function instanceOfTypeResponse(value: object): value is TypeResponse {
    return true;
}

export function TypeResponseFromJSON(json: any): TypeResponse {
    return TypeResponseFromJSONTyped(json, false);
}

export function TypeResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): TypeResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'typeId': json['typeId'] == null ? undefined : json['typeId'],
        'name': json['name'] == null ? undefined : json['name'],
    };
}

export function TypeResponseToJSON(json: any): TypeResponse {
    return TypeResponseToJSONTyped(json, false);
}

export function TypeResponseToJSONTyped(value?: TypeResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'typeId': value['typeId'],
        'name': value['name'],
    };
}

