/* tslint:disable */
/* eslint-disable */
/**
 * zzirit API
 * 찌릿 API 명세서
 *
 * The version of the OpenAPI document: v0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UploadImageRequest
 */
export interface UploadImageRequest {
    /**
     * 
     * @type {Blob}
     * @memberof UploadImageRequest
     */
    image: Blob;
}

/**
 * Check if a given object implements the UploadImageRequest interface.
 */
export function instanceOfUploadImageRequest(value: object): value is UploadImageRequest {
    if (!('image' in value) || value['image'] === undefined) return false;
    return true;
}

export function UploadImageRequestFromJSON(json: any): UploadImageRequest {
    return UploadImageRequestFromJSONTyped(json, false);
}

export function UploadImageRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): UploadImageRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'image': json['image'],
    };
}

export function UploadImageRequestToJSON(json: any): UploadImageRequest {
    return UploadImageRequestToJSONTyped(json, false);
}

export function UploadImageRequestToJSONTyped(value?: UploadImageRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'image': value['image'],
    };
}

